/**
 * Property-based tests for the {@link SchemeAssistant} response structure.
 *
 * **Property 11: Scheme Assistant Response Structure**
 * **Validates: Requirements 6.2, 6.8**
 *
 * Property statement (from design.md):
 *   "For any response generated by the Scheme_Assistant that references
 *    scheme data: (a) each referenced scheme SHALL include its official
 *    source URL and last updated date, and (b) the total response SHALL
 *    not exceed 500 words."
 *
 * The tests below exercise the property across arbitrary queries and
 * arbitrary mock-DB states using fast-check. Every external dependency
 * (Pinecone index, Prisma scheme reader, OpenAI chat client, embeddings
 * client) is replaced by an in-memory fake driven by the generated
 * inputs so the suite is hermetic.
 *
 * Properties checked:
 *   1. Word limit (b)        — answer ≤ MAX_ANSWER_WORDS for every response.
 *   2. Citation completeness — every SourceCitation has a non-empty
 *      sourceUrl string and a valid Date in lastUpdated (a).
 *   3. Source–scheme alignment — every cited schemeId belongs to the
 *      seeded DB and its sourceUrl matches the seeded record (a).
 *   4. Refusal sources are empty — REFUSAL_OFF_TOPIC and
 *      REFUSAL_NO_VERIFIED_INFO responses always carry sources = [].
 *
 * The number of runs is held to 60 — the assistant performs (mocked)
 * I/O, so each example is a touch more expensive than a pure property
 * test, but still fast.
 */

import { describe, it, expect, vi } from 'vitest';
import fc from 'fast-check';

import {
  MAX_ANSWER_WORDS,
  REFUSAL_NO_VERIFIED_INFO,
  REFUSAL_OFF_TOPIC,
  SchemeAssistant,
  type ChatCompletionsClient,
  type PineconeIndexLike,
  type SchemeReader,
  type SchemeRecord,
} from './scheme-assistant';
import {
  EMBEDDING_DIMENSIONS,
  type EmbeddingsClient,
} from '../crawler/embeddings';

const NUM_RUNS = 60;

// ─── In-memory fakes ─────────────────────────────────────────────────────────

function makeEmbeddingsClient(): EmbeddingsClient {
  // Deterministic non-zero vector — the assistant only forwards it to
  // the (also fake) Pinecone index, so its actual values are irrelevant.
  return {
    embeddings: {
      create: vi.fn(async () => ({
        data: [
          { embedding: Array.from({ length: EMBEDDING_DIMENSIONS }, () => 0.01) },
        ],
      })),
    },
  } as unknown as EmbeddingsClient;
}

interface PineconeMatch {
  id?: string;
  score?: number;
  metadata?: Record<string, unknown> | null;
}

function makePineconeIndex(matches: PineconeMatch[]): PineconeIndexLike {
  return {
    query: vi.fn(async () => ({ matches })),
  } as unknown as PineconeIndexLike;
}

function makeSchemeReader(records: SchemeRecord[]): SchemeReader {
  return {
    scheme: {
      findMany: vi.fn(async (args: { where: { id: { in: string[] } } }) => {
        const ids = new Set(args.where.id.in);
        return records.filter((r) => ids.has(r.id));
      }),
    },
  } as unknown as SchemeReader;
}

function makeOpenAI(content: string): ChatCompletionsClient {
  return {
    chat: {
      completions: {
        create: vi.fn(async () => ({
          choices: [{ message: { role: 'assistant', content } }],
        })),
      },
    },
  } as unknown as ChatCompletionsClient;
}

// ─── Arbitraries ─────────────────────────────────────────────────────────────

// A grab-bag of scheme-related keywords that flip
// `isLikelySchemeQuestion` to true. Mixing these into half of the
// generated queries gives good coverage of both the on-topic and
// off-topic refusal paths.
const SCHEME_HINT_TOKENS = [
  'scheme',
  'yojana',
  'subsidy',
  'pension',
  'scholarship',
  'eligibility',
  'apply',
  'benefit',
  'government',
  'pmkvy',
  'mgnrega',
  'kisan',
];

const arbSchemeHintedQuery: fc.Arbitrary<string> = fc
  .tuple(
    fc.constantFrom(...SCHEME_HINT_TOKENS),
    fc.string({ minLength: 0, maxLength: 80 }),
  )
  .map(([kw, suffix]) => `${kw} ${suffix}`.slice(0, 100));

const arbRandomQuery: fc.Arbitrary<string> = fc
  .string({ minLength: 5, maxLength: 100 })
  // Drop strings that are purely whitespace — answerQuery rejects those.
  .filter((s) => s.trim().length >= 1);

/**
 * Mixes scheme-keyword queries (≈⅔ of cases) with truly random ones so
 * both the verified-answer path and the refusal paths are exercised.
 */
const arbQuery: fc.Arbitrary<string> = fc.oneof(
  { weight: 2, arbitrary: arbSchemeHintedQuery },
  { weight: 1, arbitrary: arbRandomQuery },
);

/**
 * Arbitrary for a SchemeRecord with a guaranteed valid sourceUrl and
 * date fields. Generated dates avoid invalid values so `toDate` round-
 * trips deterministically.
 */
const arbDate = fc.date({
  min: new Date('2020-01-01T00:00:00Z'),
  max: new Date('2026-12-31T23:59:59Z'),
  noInvalidDate: true,
});

let _schemeIdCounter = 0;
function nextSchemeId(): string {
  _schemeIdCounter += 1;
  return `prop-scheme-${_schemeIdCounter}`;
}

const arbSchemeRecord: fc.Arbitrary<SchemeRecord> = fc
  .record({
    name: fc.string({ minLength: 1, maxLength: 60 }),
    lastVerifiedAt: fc.option(arbDate, { nil: null }),
    updatedAt: arbDate,
  })
  .map((r) => ({
    id: nextSchemeId(),
    name: r.name,
    sourceUrl: `https://example.gov.in/scheme/${_schemeIdCounter}`,
    lastVerifiedAt: r.lastVerifiedAt,
    updatedAt: r.updatedAt,
  }));

/** 1–8 distinct schemes available in the mock DB for an example. */
const arbSchemeRecords: fc.Arbitrary<SchemeRecord[]> = fc.array(arbSchemeRecord, {
  minLength: 1,
  maxLength: 8,
});

/**
 * Builds chunk matches against a list of schemes. Each chunk's score is
 * always above MIN_CHUNK_SIMILARITY (0.2), so retrieval results survive
 * the verification filter — that lets us exercise the answer path when
 * `chunkCount > 0`. When `chunkCount === 0` the assistant should refuse.
 */
function buildMatches(schemes: SchemeRecord[], chunkCount: number): PineconeMatch[] {
  if (schemes.length === 0 || chunkCount === 0) return [];
  const out: PineconeMatch[] = [];
  for (let i = 0; i < chunkCount; i += 1) {
    const scheme = schemes[i % schemes.length]!;
    out.push({
      id: `${scheme.id}-${i}`,
      score: 0.7 + (i % 3) * 0.05,
      metadata: {
        schemeId: scheme.id,
        chunkText: `Chunk ${i} for ${scheme.name}.`,
        chunkIndex: i,
      },
    });
  }
  return out;
}

/**
 * Generates LLM completion text of varying lengths so we routinely hit
 * the > MAX_ANSWER_WORDS branch and verify clamping. We bound at 800
 * words to keep generation cheap.
 */
const arbCompletionText: fc.Arbitrary<string> = fc
  .integer({ min: 1, max: 800 })
  .map((n) => Array.from({ length: n }, (_, i) => `w${i}`).join(' '));

// ─── Property 1: Word limit (Req 6.8) ────────────────────────────────────────

describe('Property 11 — Scheme Assistant Response Structure', () => {
  it('(b) every response.answer is at most MAX_ANSWER_WORDS words', async () => {
    await fc.assert(
      fc.asyncProperty(
        arbQuery,
        arbSchemeRecords,
        fc.integer({ min: 0, max: 5 }),
        arbCompletionText,
        async (query, schemes, chunkCount, completion) => {
          const matches = buildMatches(schemes, chunkCount);
          const assistant = new SchemeAssistant({
            pineconeIndex: makePineconeIndex(matches),
            prisma: makeSchemeReader(schemes),
            openai: makeOpenAI(completion),
            embeddingsClient: makeEmbeddingsClient(),
          });

          const response = await assistant.answerQuery(
            query,
            'sess-word-limit',
            'en',
          );

          const wordCount = response.answer
            .split(/\s+/)
            .filter((w) => w.length > 0).length;
          expect(wordCount).toBeLessThanOrEqual(MAX_ANSWER_WORDS);
        },
      ),
      { numRuns: NUM_RUNS },
    );
  });

  // ─── Property 2: Citation completeness (Req 6.2) ───────────────────────────

  it('(a) every SourceCitation has a non-empty sourceUrl and a valid lastUpdated Date', async () => {
    await fc.assert(
      fc.asyncProperty(
        arbQuery,
        arbSchemeRecords,
        fc.integer({ min: 0, max: 5 }),
        async (query, schemes, chunkCount) => {
          const matches = buildMatches(schemes, chunkCount);
          const assistant = new SchemeAssistant({
            pineconeIndex: makePineconeIndex(matches),
            prisma: makeSchemeReader(schemes),
            openai: makeOpenAI('A short, on-topic answer.'),
            embeddingsClient: makeEmbeddingsClient(),
          });

          const response = await assistant.answerQuery(
            query,
            'sess-citation',
            'en',
          );

          // Sources is always an array.
          expect(Array.isArray(response.sources)).toBe(true);

          for (const src of response.sources) {
            expect(typeof src.sourceUrl).toBe('string');
            expect(src.sourceUrl.length).toBeGreaterThan(0);

            expect(src.lastUpdated).toBeInstanceOf(Date);
            expect(Number.isNaN(src.lastUpdated.getTime())).toBe(false);

            expect(typeof src.schemeId).toBe('string');
            expect(src.schemeId.length).toBeGreaterThan(0);
            expect(typeof src.schemeName).toBe('string');
            expect(src.schemeName.length).toBeGreaterThan(0);
          }
        },
      ),
      { numRuns: NUM_RUNS },
    );
  });

  // ─── Property 3: Source–scheme alignment (Req 6.2) ─────────────────────────

  it('every cited schemeId resolves to a seeded scheme with a matching sourceUrl', async () => {
    await fc.assert(
      fc.asyncProperty(
        arbQuery,
        arbSchemeRecords,
        fc.integer({ min: 0, max: 5 }),
        async (query, schemes, chunkCount) => {
          const matches = buildMatches(schemes, chunkCount);
          const recordsById = new Map(schemes.map((s) => [s.id, s]));
          const assistant = new SchemeAssistant({
            pineconeIndex: makePineconeIndex(matches),
            prisma: makeSchemeReader(schemes),
            openai: makeOpenAI('A short, on-topic answer.'),
            embeddingsClient: makeEmbeddingsClient(),
          });

          const response = await assistant.answerQuery(
            query,
            'sess-alignment',
            'en',
          );

          const seenIds = new Set<string>();
          for (const src of response.sources) {
            // schemeId must come from the seeded DB.
            const rec = recordsById.get(src.schemeId);
            expect(rec).toBeDefined();
            // sourceUrl in the citation matches the DB record.
            expect(src.sourceUrl).toBe(rec!.sourceUrl);
            expect(src.schemeName).toBe(rec!.name);
            // lastUpdated falls back to updatedAt when lastVerifiedAt is null.
            const expectedDate = rec!.lastVerifiedAt ?? rec!.updatedAt;
            const expectedIso =
              expectedDate instanceof Date
                ? expectedDate.toISOString()
                : new Date(expectedDate).toISOString();
            expect(src.lastUpdated.toISOString()).toBe(expectedIso);

            // Citations are deduplicated by schemeId.
            expect(seenIds.has(src.schemeId)).toBe(false);
            seenIds.add(src.schemeId);
          }
        },
      ),
      { numRuns: NUM_RUNS },
    );
  });

  // ─── Property 4: Refusal sources are empty ─────────────────────────────────

  it('refusal responses (off-topic / no verified info) carry an empty sources array', async () => {
    await fc.assert(
      fc.asyncProperty(
        arbQuery,
        arbSchemeRecords,
        fc.integer({ min: 0, max: 5 }),
        async (query, schemes, chunkCount) => {
          const matches = buildMatches(schemes, chunkCount);
          const assistant = new SchemeAssistant({
            pineconeIndex: makePineconeIndex(matches),
            prisma: makeSchemeReader(schemes),
            openai: makeOpenAI('Should not be used in refusal paths.'),
            embeddingsClient: makeEmbeddingsClient(),
          });

          const response = await assistant.answerQuery(
            query,
            'sess-refusal',
            'en',
          );

          if (
            response.answer === REFUSAL_OFF_TOPIC ||
            response.answer === REFUSAL_NO_VERIFIED_INFO
          ) {
            expect(response.sources).toEqual([]);
          }
        },
      ),
      { numRuns: NUM_RUNS },
    );
  });
});
