-- ─────────────────────────────────────────────────────────────────────────────
--  Convert `audit_logs` to a monthly-partitioned table.
--
--  Why
--  --
--  Audit logs are append-only and retained for ≥ 365 days (Req 16.6). Without
--  partitioning the table grows linearly forever, every retention sweep does
--  a `DELETE` over the entire bottom of the index, and `pg_dump` /
--  `pg_restore` copies hundreds of millions of rows in a single chunk.
--
--  Partitioning by month gives us:
--    1. O(1) retention pruning — drop the oldest partition instead of
--       scanning the table for `timestamp < cutoff`.
--    2. Smaller indexes per partition → faster lookups for recent traffic.
--    3. Cheaper backups — vacuum, analyse, and dump operate per partition.
--
--  Approach
--  --------
--  PostgreSQL only allows declarative-partitioned tables to be created from
--  scratch. We:
--    1. Rename the existing `audit_logs` to `audit_logs_legacy`.
--    2. Create a new partitioned `audit_logs` parent table.
--    3. Create the initial partitions (current month + the next 12 months,
--       plus a catch-all `default` partition for late-arriving rows).
--    4. Copy all rows from the legacy table to the new partitioned one.
--    5. Drop the legacy table.
--
--  Step (3) is intentionally generous: a single year of partitions means the
--  ops team has ~12 months of runway to wire up the monthly partition-creation
--  job before late-month rows start landing in the catch-all. Once the job
--  is in place, schedule it to run on the 25th of each month creating
--  `audit_logs_yYYYY_mMM` for two months ahead.
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. Stash the existing table.
ALTER TABLE "audit_logs" RENAME TO "audit_logs_legacy";

-- The unique-id constraint name on the legacy table is auto-generated by
-- Prisma; rename it so the new table can reuse the canonical name.
ALTER INDEX IF EXISTS "audit_logs_pkey" RENAME TO "audit_logs_legacy_pkey";

-- 2. Create the new partitioned parent.
CREATE TABLE "audit_logs" (
  "id"             uuid        NOT NULL DEFAULT uuid_generate_v4(),
  "user_id"        uuid,
  "action"         text        NOT NULL,
  "resource_type"  text        NOT NULL,
  "resource_id"    uuid,
  "details"        jsonb,
  "actor_identity" text,
  "timestamp"      timestamptz NOT NULL DEFAULT now(),
  -- Partitioning key MUST be part of the primary key in PostgreSQL
  -- declarative partitioning, so the PK is composite (id, timestamp).
  CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id", "timestamp")
) PARTITION BY RANGE ("timestamp");

-- Indexes on the parent table propagate to every child partition.
CREATE INDEX "idx_audit_log_user_id"   ON "audit_logs" ("user_id");
CREATE INDEX "idx_audit_log_resource"  ON "audit_logs" ("resource_type", "resource_id");
CREATE INDEX "idx_audit_log_timestamp" ON "audit_logs" ("timestamp");

-- 3. Initial partitions. The DO-block builds 14 monthly partitions starting
-- from the first day of last month so any rows the legacy table holds for
-- the previous month land cleanly. A `default` partition catches anything
-- outside the explicit ranges so the import in step 4 cannot fail.
DO $$
DECLARE
  start_month date := date_trunc('month', now())::date - interval '1 month';
  i           int;
  part_start  date;
  part_end    date;
  part_name   text;
BEGIN
  FOR i IN 0..13 LOOP
    part_start := (start_month + (i || ' month')::interval)::date;
    part_end   := (start_month + ((i + 1) || ' month')::interval)::date;
    part_name  := format('audit_logs_y%sm%s',
                         to_char(part_start, 'YYYY'),
                         to_char(part_start, 'MM'));
    EXECUTE format(
      'CREATE TABLE %I PARTITION OF "audit_logs" FOR VALUES FROM (%L) TO (%L)',
      part_name, part_start, part_end);
  END LOOP;
END $$;

-- Default partition for late or out-of-range rows. The ops team should
-- monitor `pg_class` for non-empty default partitions — anything that
-- lands here is missing a real partition and should be migrated.
CREATE TABLE "audit_logs_default" PARTITION OF "audit_logs" DEFAULT;

-- 4. Copy data from the legacy table into the new partitioned one.
-- Postgres routes each row to the correct partition based on `timestamp`.
INSERT INTO "audit_logs" (
  "id", "user_id", "action", "resource_type", "resource_id",
  "details", "actor_identity", "timestamp"
)
SELECT
  "id", "user_id", "action", "resource_type", "resource_id",
  "details", "actor_identity", "timestamp"
FROM "audit_logs_legacy";

-- Restore the FK from `users.id` (Prisma will recreate it on next
-- generate, but we add it manually here so the data is consistent
-- immediately after the migration).
ALTER TABLE "audit_logs"
  ADD CONSTRAINT "audit_logs_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL;

-- 5. Drop the legacy table.
DROP TABLE "audit_logs_legacy";
