/**
 * Property-based tests for the Recommendation Engine output invariants.
 *
 * **Property 9: Recommendation Output Invariants**
 * **Validates: Requirements 5.2, 5.6, 5.7**
 *
 * Property statement (from design.md):
 * "For any recommendation generated by the Recommendation_Engine:
 *   (a) the Match_Score SHALL be an integer in [0, 100],
 *   (b) the explanation string SHALL be at most 200 characters, and
 *   (c) the total recommendation list SHALL contain at most 50 schemes."
 *
 * The tests below exercise each clause across arbitrary, valid inputs:
 *   - Per-pair invariants (a) and (b) are verified by driving the pure
 *     scoring/explanation helpers directly with fast-check generators.
 *   - The list cap (c) and the in-list per-recommendation invariants are
 *     verified end-to-end through `RecommendationEngine.generateRecommendations`
 *     with an in-memory fake of the Prisma surface the engine consumes.
 */

import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import {
  PROFILE_CONSTRAINTS,
  INDIAN_STATES,
  MAX_RECOMMENDATIONS,
  MAX_RECOMMENDATION_EXPLANATION_CHARS,
  type UserProfile,
  type Scheme,
  type SchemeCategory,
  type EligibilityCriterion,
  type Gender,
  type Occupation,
  type CasteCategory,
  type MaritalStatus,
  type EducationLevel,
  type SupportedLanguage,
} from '@bharat-benefits/shared';
import {
  RecommendationEngine,
  calculateMatchScore,
  generateExplanation,
  type RecommendationEnginePrisma,
} from './recommendation-engine';
import { calculateEligibility } from '../eligibility';

const NUM_RUNS = 120;
// The list-cap property runs the full engine over up to 200 schemes per
// example, so we keep its sample budget on the lower end to stay fast.
const NUM_RUNS_LIST = 60;

// ─── Profile arbitraries ─────────────────────────────────────────────────────

const arbGender = fc.constantFrom<Gender>(
  ...(PROFILE_CONSTRAINTS.gender as Gender[]),
);
const arbOccupation = fc.constantFrom<Occupation>(
  ...(PROFILE_CONSTRAINTS.occupation as Occupation[]),
);
const arbCaste = fc.constantFrom<CasteCategory>(
  ...(PROFILE_CONSTRAINTS.caste as CasteCategory[]),
);
const arbMarital = fc.constantFrom<MaritalStatus>(
  ...(PROFILE_CONSTRAINTS.maritalStatus as MaritalStatus[]),
);
const arbEducation = fc.constantFrom<EducationLevel>(
  ...(PROFILE_CONSTRAINTS.education as EducationLevel[]),
);
const arbState = fc.constantFrom(...INDIAN_STATES);
const arbLanguage = fc.constantFrom<SupportedLanguage>(
  'en',
  'hi',
  'bn',
  'ta',
  'te',
  'mr',
);

const arbAge = fc.integer({ min: 0, max: 150 });
const arbIncome = fc.integer({ min: 0, max: 9_999_999_999 });
const arbDependents = fc.integer({ min: 0, max: 20 });

/**
 * Fully populated, valid `UserProfile`. Optional demographic fields are kept
 * non-null so eligibility/score paths that depend on them (e.g. occupation
 * → category alignment) are exercised regularly.
 */
const arbValidProfile: fc.Arbitrary<UserProfile> = fc.record({
  id: fc.string({ minLength: 1, maxLength: 32 }),
  userId: fc.string({ minLength: 1, maxLength: 32 }),
  age: arbAge,
  gender: arbGender,
  state: arbState,
  district: fc.option(fc.string({ minLength: 1, maxLength: 40 }), { nil: null }),
  incomeLevel: arbIncome,
  occupation: arbOccupation,
  educationLevel: arbEducation,
  casteCategory: arbCaste,
  disabilityStatus: fc.boolean(),
  maritalStatus: arbMarital,
  dependents: arbDependents,
  languagePreference: arbLanguage,
  updatedAt: fc.date({ noInvalidDate: true }),
});

// ─── Criterion arbitraries ───────────────────────────────────────────────────

const arbDescription = fc.string({ minLength: 1, maxLength: 80 });

/** Categorical eq / neq criteria over enum-valued profile fields. */
const arbCategoricalEqNeq: fc.Arbitrary<EligibilityCriterion> = fc.oneof(
  fc.record({
    field: fc.constant('gender'),
    operator: fc.constantFrom('eq', 'neq'),
    value: arbGender,
    description: arbDescription,
  }),
  fc.record({
    field: fc.constant('casteCategory'),
    operator: fc.constantFrom('eq', 'neq'),
    value: arbCaste,
    description: arbDescription,
  }),
  fc.record({
    field: fc.constant('occupation'),
    operator: fc.constantFrom('eq', 'neq'),
    value: arbOccupation,
    description: arbDescription,
  }),
  fc.record({
    field: fc.constant('maritalStatus'),
    operator: fc.constantFrom('eq', 'neq'),
    value: arbMarital,
    description: arbDescription,
  }),
) as fc.Arbitrary<EligibilityCriterion>;

const arbCategoricalIn: fc.Arbitrary<EligibilityCriterion> = fc.oneof(
  fc.record({
    field: fc.constant('gender'),
    operator: fc.constant('in'),
    value: fc.array(arbGender, { minLength: 1, maxLength: 3 }),
    description: arbDescription,
  }),
  fc.record({
    field: fc.constant('casteCategory'),
    operator: fc.constant('in'),
    value: fc.array(arbCaste, { minLength: 1, maxLength: 4 }),
    description: arbDescription,
  }),
  fc.record({
    field: fc.constant('occupation'),
    operator: fc.constant('in'),
    value: fc.array(arbOccupation, { minLength: 1, maxLength: 7 }),
    description: arbDescription,
  }),
) as fc.Arbitrary<EligibilityCriterion>;

const arbNumericComparison: fc.Arbitrary<EligibilityCriterion> = fc.oneof(
  fc.record({
    field: fc.constant('age'),
    operator: fc.constantFrom('gt', 'gte', 'lt', 'lte'),
    value: arbAge,
    description: arbDescription,
  }),
  fc.record({
    field: fc.constant('income'),
    operator: fc.constantFrom('gt', 'gte', 'lt', 'lte'),
    value: arbIncome,
    description: arbDescription,
  }),
) as fc.Arbitrary<EligibilityCriterion>;

const arbBetween: fc.Arbitrary<EligibilityCriterion> = fc.oneof(
  fc.tuple(arbAge, arbAge, arbDescription).map(
    ([a, b, desc]): EligibilityCriterion => ({
      field: 'age',
      operator: 'between',
      value: [Math.min(a, b), Math.max(a, b)],
      description: desc,
    }),
  ),
  fc.tuple(arbIncome, arbIncome, arbDescription).map(
    ([a, b, desc]): EligibilityCriterion => ({
      field: 'income',
      operator: 'between',
      value: [Math.min(a, b), Math.max(a, b)],
      description: desc,
    }),
  ),
);

const arbCriterion: fc.Arbitrary<EligibilityCriterion> = fc.oneof(
  arbCategoricalEqNeq,
  arbCategoricalIn,
  arbNumericComparison,
  arbBetween,
);

// ─── Scheme arbitrary ────────────────────────────────────────────────────────

const arbCategory: fc.Arbitrary<SchemeCategory> = fc.constantFrom<SchemeCategory>(
  'Education',
  'Agriculture',
  'Healthcare',
  'Women',
  'Employment',
  'Skill Development',
  'Housing',
  'Startups',
  'MSME',
  'Pension',
  'Scholarships',
  'Financial Assistance',
);

/**
 * State for a scheme: null (Central) or any valid Indian state. Including
 * null at ~25% drives coverage of the 'central' priority group.
 */
const arbSchemeState: fc.Arbitrary<string | null> = fc.option(arbState, {
  nil: null,
  freq: 4,
});

/**
 * Recent-ish dates so the recency bonus path is regularly exercised. We
 * mix in older dates to also drive the "not recent" path.
 */
const arbSchemeDate = fc.date({
  min: new Date('2020-01-01T00:00:00Z'),
  max: new Date('2026-12-31T23:59:59Z'),
  noInvalidDate: true,
});

/** Optional finite benefit amount up to ~₹10 Cr; null is common too. */
const arbBenefitAmount = fc.option(fc.integer({ min: 0, max: 100_000_000 }), {
  nil: null,
});

/** Optional deadline; mix of past, near-term, and far-future dates. */
const arbDeadline = fc.option(arbSchemeDate, { nil: null });

const arbBenefitType = fc.constantFrom<'monetary' | 'non-monetary'>(
  'monetary',
  'non-monetary',
);
const arbApplicationMode = fc.constantFrom<'online' | 'offline' | 'hybrid'>(
  'online',
  'offline',
  'hybrid',
);

let _schemeIdCounter = 0;
function nextSchemeId(): string {
  _schemeIdCounter += 1;
  return `s-${_schemeIdCounter}`;
}

/**
 * Builds a minimal but valid `Scheme`. Trust score is fixed at >= 60 so the
 * engine's citizen-visible filter (Req 1.6) doesn't drop schemes during the
 * end-to-end list-cap property.
 */
const arbScheme: fc.Arbitrary<Scheme> = fc
  .record({
    id: fc.string({ minLength: 1, maxLength: 24 }),
    name: fc.string({ minLength: 1, maxLength: 60 }),
    description: fc.string({ minLength: 0, maxLength: 200 }),
    ministry: fc.string({ minLength: 1, maxLength: 60 }),
    state: arbSchemeState,
    category: arbCategory,
    benefitType: arbBenefitType,
    benefitAmount: arbBenefitAmount,
    deadline: arbDeadline,
    applicationMode: arbApplicationMode,
    eligibilityCriteria: fc.array(arbCriterion, { minLength: 0, maxLength: 6 }),
    trustScore: fc.integer({ min: 60, max: 100 }),
    verified: fc.boolean(),
    discoveredAt: arbSchemeDate,
    lastVerifiedAt: arbSchemeDate,
    updatedAt: arbSchemeDate,
  })
  .map(
    (r): Scheme => ({
      id: r.id,
      name: r.name,
      description: r.description,
      ministry: r.ministry,
      state: r.state,
      category: r.category,
      sourceUrl: `https://example.gov.in/${encodeURIComponent(r.id)}`,
      benefitType: r.benefitType,
      benefitAmount: r.benefitAmount,
      deadline: r.deadline,
      applicationMode: r.applicationMode,
      applicationUrl: null,
      eligibilityCriteria: r.eligibilityCriteria,
      benefits: [],
      applicationSteps: null,
      requiredDocuments: null,
      trustScore: r.trustScore,
      verified: r.verified,
      discoveredAt: r.discoveredAt,
      lastVerifiedAt: r.lastVerifiedAt,
      updatedAt: r.updatedAt,
    }),
  );

/**
 * Variant that guarantees globally unique scheme ids — required for the
 * end-to-end list property where duplicate ids would alias each other in
 * the engine's stable tie-breaker.
 */
const arbSchemeUnique: fc.Arbitrary<Scheme> = arbScheme.map((s) => ({
  ...s,
  id: nextSchemeId(),
}));

/** A list of 0–200 schemes, every id distinct. */
const arbSchemeList: fc.Arbitrary<Scheme[]> = fc.array(arbSchemeUnique, {
  minLength: 0,
  maxLength: 200,
});

// ─── Fake Prisma client ──────────────────────────────────────────────────────

function fakeDb(profile: UserProfile, schemes: Scheme[]): RecommendationEnginePrisma {
  return {
    userProfile: {
      async findUnique({ where }) {
        return profile.userId === where.userId ? profile : null;
      },
    },
    scheme: {
      async findMany({ where }) {
        if (!where) return schemes;
        const min = where.trustScore?.gte ?? 0;
        return schemes.filter((s) => s.trustScore >= min);
      },
    },
  };
}

// ─── Property Tests ──────────────────────────────────────────────────────────

describe('Property 9: Recommendation Output Invariants', () => {
  // (a) Match_Score is an integer in [0, 100] for any (profile, scheme).
  it('(a) calculateMatchScore returns an integer in [0, 100] for any valid profile/scheme', () => {
    fc.assert(
      fc.property(arbValidProfile, arbScheme, (profile, scheme) => {
        const score = calculateMatchScore(profile, scheme);
        expect(Number.isInteger(score)).toBe(true);
        expect(score).toBeGreaterThanOrEqual(0);
        expect(score).toBeLessThanOrEqual(100);
      }),
      { numRuns: NUM_RUNS },
    );
  });

  // (b) Explanation string is at most MAX_RECOMMENDATION_EXPLANATION_CHARS.
  it('(b) generateExplanation returns a string of length <= 200', () => {
    fc.assert(
      fc.property(arbValidProfile, arbScheme, (profile, scheme) => {
        const eligibility = calculateEligibility(profile, scheme);
        const score = calculateMatchScore(profile, scheme, eligibility);
        const explanation = generateExplanation(profile, scheme, eligibility, score);
        expect(typeof explanation).toBe('string');
        expect(explanation.length).toBeLessThanOrEqual(
          MAX_RECOMMENDATION_EXPLANATION_CHARS,
        );
      }),
      { numRuns: NUM_RUNS },
    );
  });

  // (c) Recommendation list contains at most MAX_RECOMMENDATIONS schemes.
  it('(c) generateRecommendations returns at most 50 schemes for any list of 0–200 schemes', async () => {
    await fc.assert(
      fc.asyncProperty(arbValidProfile, arbSchemeList, async (profile, schemes) => {
        const engine = new RecommendationEngine(fakeDb(profile, schemes));
        const recs = await engine.generateRecommendations(profile.userId);
        expect(Array.isArray(recs)).toBe(true);
        expect(recs.length).toBeLessThanOrEqual(MAX_RECOMMENDATIONS);
      }),
      { numRuns: NUM_RUNS_LIST },
    );
  });

  // (a) + (b) lifted to every entry of an end-to-end recommendation list,
  // plus the structural shape required by the Recommendation interface.
  it('every recommendation in the engine output satisfies the per-item invariants', async () => {
    await fc.assert(
      fc.asyncProperty(arbValidProfile, arbSchemeList, async (profile, schemes) => {
        const engine = new RecommendationEngine(fakeDb(profile, schemes));
        const recs = await engine.generateRecommendations(profile.userId);

        // Each scheme id used in the input list — used to verify the
        // engine never invents a schemeId.
        const validIds = new Set(schemes.map((s) => s.id));

        for (const r of recs) {
          // matchScore: integer in [0, 100].
          expect(Number.isInteger(r.matchScore)).toBe(true);
          expect(r.matchScore).toBeGreaterThanOrEqual(0);
          expect(r.matchScore).toBeLessThanOrEqual(100);

          // explanation: string, length <= 200.
          expect(typeof r.explanation).toBe('string');
          expect(r.explanation.length).toBeLessThanOrEqual(
            MAX_RECOMMENDATION_EXPLANATION_CHARS,
          );

          // benefitAmount: number or null.
          expect(
            r.benefitAmount === null || typeof r.benefitAmount === 'number',
          ).toBe(true);

          // deadline: Date or null.
          expect(r.deadline === null || r.deadline instanceof Date).toBe(true);

          // priorityGroup: one of 'state' | 'central' | 'other'.
          expect(['state', 'central', 'other']).toContain(r.priorityGroup);

          // schemeId: non-empty string drawn from the input set.
          expect(typeof r.schemeId).toBe('string');
          expect(r.schemeId.length).toBeGreaterThan(0);
          expect(validIds.has(r.schemeId)).toBe(true);
        }
      }),
      { numRuns: NUM_RUNS_LIST },
    );
  });
});
