/**
 * Batch 2: Education, Scholarships, Women, Housing, Pension, Insurance schemes.
 */

import type { SeedScheme } from './seed-data';

const D = {
  aadhaar: { documentName: 'Aadhaar Card', description: '12-digit UIDAI identification', format: 'Original or photocopy', required: true },
  pan: { documentName: 'PAN Card', description: 'Permanent Account Number', format: 'Original or photocopy', required: true },
  bank: { documentName: 'Bank Account Passbook', description: 'Active bank account', format: 'First page', required: true },
  income: { documentName: 'Income Certificate', description: 'Issued by Tehsildar', format: 'Recent', required: true },
  domicile: { documentName: 'Domicile Proof', description: 'Proof of state residence', format: 'Voter ID/utility bill', required: true },
  photo: { documentName: 'Passport-Size Photograph', description: 'Recent photograph', format: 'JPEG/PNG', required: true },
  caste: { documentName: 'Caste Certificate', description: 'For SC/ST/OBC', format: 'From competent authority', required: false },
  ration: { documentName: 'Ration Card', description: 'BPL/AAY ration card', format: 'Original', required: true },
  birth: { documentName: 'Birth Certificate', description: 'Municipal/panchayat issued', format: 'Original', required: true },
  marksheet: { documentName: 'Latest Mark Sheet', description: 'Most recent academic record', format: 'Original', required: true },
  bonafide: { documentName: 'Bonafide Certificate', description: 'From educational institution', format: 'Original', required: true },
};

export const SCHEMES_BATCH_2: SeedScheme[] = [
  // ─── EDUCATION (8) ────────────────────────────────────────────────
  {
    slug: 'mid-day-meal',
    name: 'PM POSHAN (Mid-Day Meal Scheme)',
    description: 'Provides nutritious cooked mid-day meals to school children in classes I to VIII in government and government-aided schools.',
    ministry: 'Ministry of Education',
    state: null, category: 'Education',
    sourceUrl: 'https://pmposhan.education.gov.in/',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [{ field: 'age', operator: 'between', value: [6, 14], description: 'Children 6-14 in classes I-VIII' }],
    applicationSteps: [{ stepNumber: 1, action: 'Enroll child in government/aided school', expectedOutcome: 'Auto-eligible — meal served on every school day' }],
    documents: [D.aadhaar, { documentName: 'School ID', description: 'Government school enrollment', format: 'Original', required: true }],
    trustScore: 95,
  },
  {
    slug: 'samagra-shiksha',
    name: 'Samagra Shiksha Abhiyan',
    description: 'Integrated scheme covering pre-school to senior secondary with focus on quality education, equity, and inclusion. Free textbooks, uniforms, transport.',
    ministry: 'Ministry of Education',
    state: null, category: 'Education',
    sourceUrl: 'https://samagra.education.gov.in/',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [{ field: 'age', operator: 'between', value: [3, 18], description: 'Children 3-18 in eligible schools' }],
    applicationSteps: [{ stepNumber: 1, action: 'Enroll in government/aided school', expectedOutcome: 'Benefits provided automatically' }],
    documents: [D.aadhaar, { documentName: 'School Admission Certificate', description: 'Enrollment proof', format: 'Original', required: true }],
    trustScore: 92,
  },
  {
    slug: 'pm-vidya-lakshmi',
    name: 'Vidya Lakshmi Education Loan Portal',
    description: 'Single-window portal for education loans connecting students with multiple banks. Loans up to Rs. 10 lakh at concessional rates with no collateral up to Rs. 7.5 lakh.',
    ministry: 'Ministry of Finance',
    state: null, category: 'Scholarships',
    sourceUrl: 'https://www.vidyalakshmi.co.in/',
    benefitType: 'monetary', benefitAmount: 1000000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://www.vidyalakshmi.co.in/',
    eligibilityCriteria: [
      { field: 'age', operator: 'between', value: [16, 35], description: 'Indian student admitted to recognized institution' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at vidyalakshmi.co.in', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Fill Common Education Loan Application Form (CELAF)', expectedOutcome: 'Application sent to selected banks' },
      { stepNumber: 3, action: 'Bank approves and disburses loan', expectedOutcome: 'Funds credited' },
    ],
    documents: [D.aadhaar, D.pan, { documentName: 'Admission Letter', description: 'From recognized institution', format: 'Original', required: true }, D.marksheet],
    trustScore: 92,
  },
  {
    slug: 'aicte-pragati',
    name: 'AICTE Pragati Scholarship for Girls',
    description: 'Scholarship of Rs. 50,000 per year for 4,000 girl students in technical education (degree/diploma) from families with income below Rs. 8 lakh.',
    ministry: 'Ministry of Education',
    state: null, category: 'Scholarships',
    sourceUrl: 'https://www.aicte-pragati-saksham-gov.in/',
    benefitType: 'monetary', benefitAmount: 50000,
    deadline: new Date('2026-10-31'),
    applicationMode: 'online', applicationUrl: 'https://www.aicte-pragati-saksham-gov.in/',
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Female student' },
      { field: 'incomeLevel', operator: 'lte', value: 800000, description: 'Family income below Rs. 8 lakh' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at AICTE Pragati portal', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Apply with academic and income details', expectedOutcome: 'Application submitted' },
      { stepNumber: 3, action: 'Get verified by institute', expectedOutcome: 'Scholarship credited' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.marksheet, D.bonafide],
    trustScore: 92,
  },
  {
    slug: 'aicte-saksham',
    name: 'AICTE Saksham Scholarship for Differently-Abled Students',
    description: 'Scholarship of Rs. 50,000 per year for 1,000 specially-abled students pursuing technical education from families with income below Rs. 8 lakh.',
    ministry: 'Ministry of Education',
    state: null, category: 'Scholarships',
    sourceUrl: 'https://www.aicte-pragati-saksham-gov.in/saksham',
    benefitType: 'monetary', benefitAmount: 50000,
    deadline: new Date('2026-10-31'),
    applicationMode: 'online', applicationUrl: 'https://www.aicte-pragati-saksham-gov.in/saksham',
    eligibilityCriteria: [
      { field: 'disabilityStatus', operator: 'eq', value: true, description: 'Disability of 40% or more' },
      { field: 'incomeLevel', operator: 'lte', value: 800000, description: 'Family income below Rs. 8 lakh' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at AICTE Saksham portal', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Apply with disability and income proof', expectedOutcome: 'Application submitted' },
      { stepNumber: 3, action: 'Receive scholarship after verification', expectedOutcome: 'Funds credited' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.marksheet, { documentName: 'Disability Certificate', description: 'Issued by competent authority', format: 'Original', required: true }],
    trustScore: 92,
  },
  {
    slug: 'national-scholarship',
    name: 'National Scholarship Portal (NSP)',
    description: 'Unified portal providing scholarships to minority, SC, ST, OBC, EWS students for pre-matric, post-matric, and merit-cum-means courses.',
    ministry: 'Ministry of Electronics and Information Technology',
    state: null, category: 'Scholarships',
    sourceUrl: 'https://scholarships.gov.in/',
    benefitType: 'monetary', benefitAmount: 50000,
    deadline: new Date('2026-10-31'),
    applicationMode: 'online', applicationUrl: 'https://scholarships.gov.in/',
    eligibilityCriteria: [
      { field: 'age', operator: 'between', value: [10, 35], description: 'Student aged 10-35' },
      { field: 'incomeLevel', operator: 'lte', value: 250000, description: 'Income below Rs. 2.5 lakh' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at scholarships.gov.in', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Fill the application and upload documents', expectedOutcome: 'Application submitted' },
      { stepNumber: 3, action: 'Institute and authorities verify', expectedOutcome: 'Scholarship via DBT' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.marksheet, D.bonafide, D.caste],
    trustScore: 92,
  },
  {
    slug: 'inspire-scholarship',
    name: 'INSPIRE Scholarship for Higher Education (SHE)',
    description: 'Awards Rs. 80,000 per year to top 1% of class XII students pursuing natural and basic sciences (BSc/MSc) at recognized institutions.',
    ministry: 'Department of Science and Technology',
    state: null, category: 'Scholarships',
    sourceUrl: 'https://online-inspire.gov.in/',
    benefitType: 'monetary', benefitAmount: 80000,
    deadline: new Date('2026-09-30'),
    applicationMode: 'online', applicationUrl: 'https://online-inspire.gov.in/',
    eligibilityCriteria: [
      { field: 'age', operator: 'lte', value: 22, description: 'Top 1% in Class XII pursuing BSc/MSc' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at online-inspire.gov.in', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Submit Class XII marks and admission proof', expectedOutcome: 'Application submitted' },
      { stepNumber: 3, action: 'Get scholarship credited annually', expectedOutcome: 'Rs. 80,000/year for 5 years' },
    ],
    documents: [D.aadhaar, D.bank, D.marksheet, D.bonafide],
    trustScore: 92,
  },
  {
    slug: 'beti-bachao-padhao',
    name: 'Beti Bachao Beti Padhao',
    description: 'Flagship scheme preventing gender-biased sex selection, ensuring survival, protection and education of the girl child.',
    ministry: 'Ministry of Women and Child Development',
    state: null, category: 'Education',
    sourceUrl: 'https://wcd.nic.in/bbbp-schemes',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Girl child' },
      { field: 'age', operator: 'lte', value: 18, description: 'Up to 18 years' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit nearest Anganwadi or Block Development Office', expectedOutcome: 'Officer assigned' },
      { stepNumber: 2, action: 'Submit application with birth certificate', expectedOutcome: 'Registered' },
    ],
    documents: [D.birth, D.aadhaar, D.domicile],
    trustScore: 90,
  },

  // ─── WOMEN (8) ────────────────────────────────────────────────────
  {
    slug: 'sukanya-samriddhi',
    name: 'Sukanya Samriddhi Yojana (SSY)',
    description: 'Small deposit savings scheme for the girl child. 8.2% interest rate (highest among small savings). Tax benefits under Section 80C.',
    ministry: 'Ministry of Finance',
    state: null, category: 'Women',
    sourceUrl: 'https://www.india.gov.in/sukanya-samriddhi-yojna',
    benefitType: 'monetary', benefitAmount: 1500000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Girl child' },
      { field: 'age', operator: 'lte', value: 10, description: 'Below 10 years' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit post office or authorized bank', expectedOutcome: 'Form obtained' },
      { stepNumber: 2, action: 'Open account with parent/guardian', expectedOutcome: 'Account active' },
      { stepNumber: 3, action: 'Deposit Rs. 250 to Rs. 1.5 lakh annually', expectedOutcome: 'Account active until girl turns 21' },
    ],
    documents: [D.birth, D.aadhaar, { documentName: 'Guardian Address Proof', description: 'Aadhaar/utility bill', format: 'Original', required: true }],
    trustScore: 95,
  },
  {
    slug: 'pm-ujjwala',
    name: 'Pradhan Mantri Ujjwala Yojana (PMUY)',
    description: 'Free LPG connections to women from BPL households. Deposit-free connections worth Rs. 1,600 plus first refill assistance.',
    ministry: 'Ministry of Petroleum and Natural Gas',
    state: null, category: 'Women',
    sourceUrl: 'https://www.pmuy.gov.in/',
    benefitType: 'non-monetary', benefitAmount: 1600, deadline: null,
    applicationMode: 'offline', applicationUrl: 'https://www.pmuy.gov.in/ujjwala2.html',
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Woman' },
      { field: 'age', operator: 'gte', value: 18, description: '18+' },
      { field: 'incomeLevel', operator: 'lte', value: 200000, description: 'BPL household' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit nearest LPG distributor', expectedOutcome: 'Distributor identified' },
      { stepNumber: 2, action: 'Submit KYC form and documents', expectedOutcome: 'Form submitted' },
      { stepNumber: 3, action: 'Receive connection within 15 days', expectedOutcome: 'Cylinder, regulator delivered' },
    ],
    documents: [D.aadhaar, D.bank, D.ration, D.photo],
    trustScore: 95,
  },
  {
    slug: 'mahila-samman',
    name: 'Mahila Samman Savings Certificate (MSSC)',
    description: '7.5% per annum interest savings scheme for women, deposits up to Rs. 2 lakh, 2-year tenure with partial withdrawal option after 1 year.',
    ministry: 'Ministry of Finance',
    state: null, category: 'Women',
    sourceUrl: 'https://www.indiapost.gov.in/Financial/pages/content/mssc.aspx',
    benefitType: 'monetary', benefitAmount: 200000,
    deadline: new Date('2027-03-31'),
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [{ field: 'gender', operator: 'eq', value: 'Female', description: 'Woman or girl' }],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit any post office', expectedOutcome: 'Form available' },
      { stepNumber: 2, action: 'Fill MSSC form and submit KYC', expectedOutcome: 'Form submitted' },
      { stepNumber: 3, action: 'Make deposit', expectedOutcome: 'Certificate issued' },
    ],
    documents: [D.aadhaar, D.pan, D.photo],
    trustScore: 92,
  },
  {
    slug: 'mahila-shakti-kendra',
    name: 'Mahila Shakti Kendra (MSK)',
    description: 'Empowerment programme for rural women through community participation. Provides skill development, employment, and digital literacy at block-level centres.',
    ministry: 'Ministry of Women and Child Development',
    state: null, category: 'Women',
    sourceUrl: 'https://wcd.nic.in/schemes/mahila-shakti-kendra-msk',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Rural women' },
      { field: 'age', operator: 'gte', value: 18, description: '18+' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit nearest Mahila Shakti Kendra at block level', expectedOutcome: 'Free services and counselling' },
    ],
    documents: [D.aadhaar],
    trustScore: 85,
  },
  {
    slug: 'one-stop-centre',
    name: 'One Stop Centre Scheme (Sakhi)',
    description: 'Integrated support for women affected by violence — medical, legal, psychological, police assistance and temporary shelter under one roof.',
    ministry: 'Ministry of Women and Child Development',
    state: null, category: 'Women',
    sourceUrl: 'https://wcd.nic.in/schemes/one-stop-centre-scheme-1',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Women affected by violence (any age)' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Call women helpline 181 or visit nearest OSC', expectedOutcome: 'Immediate assistance' },
    ],
    documents: [D.aadhaar],
    trustScore: 92,
  },
  {
    slug: 'maternity-benefit',
    name: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
    description: 'Maternity benefit of Rs. 5,000 in three installments to pregnant and lactating mothers for first child. Wage compensation for partial wage loss.',
    ministry: 'Ministry of Women and Child Development',
    state: null, category: 'Women',
    sourceUrl: 'https://wcd.nic.in/schemes/pradhan-mantri-matru-vandana-yojana',
    benefitType: 'monetary', benefitAmount: 5000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Pregnant/lactating mother (first child)' },
      { field: 'age', operator: 'gte', value: 19, description: '19+' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register pregnancy at Anganwadi', expectedOutcome: 'Registered' },
      { stepNumber: 2, action: 'Submit forms 1A, 1B, 1C as milestones met', expectedOutcome: 'Installments credited' },
    ],
    documents: [D.aadhaar, D.bank, { documentName: 'MCP Card', description: 'Mother and Child Protection Card', format: 'Original', required: true }],
    trustScore: 92,
  },
  {
    slug: 'working-women-hostel',
    name: 'Working Women Hostel Scheme',
    description: 'Provides safe, affordable accommodation for working women near workplace, with day-care for their children where possible.',
    ministry: 'Ministry of Women and Child Development',
    state: null, category: 'Women',
    sourceUrl: 'https://wcd.nic.in/schemes/working-women-hostel',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Working women' },
      { field: 'age', operator: 'gte', value: 18, description: '18+' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply at nearest WWH', expectedOutcome: 'Allotment based on availability' },
    ],
    documents: [D.aadhaar, { documentName: 'Employment Proof', description: 'Letter from employer', format: 'Original', required: true }],
    trustScore: 85,
  },
  {
    slug: 'swadhar-greh',
    name: 'Swadhar Greh Scheme',
    description: 'Provides shelter, food, clothing, counselling and rehabilitation to women in difficult circumstances (widows, destitute, victims of trafficking).',
    ministry: 'Ministry of Women and Child Development',
    state: null, category: 'Women',
    sourceUrl: 'https://wcd.nic.in/schemes/swadhar-greh',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Women in distress (any age)' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Approach Swadhar Greh shelter or contact 181', expectedOutcome: 'Admission and rehabilitation' },
    ],
    documents: [D.aadhaar],
    trustScore: 88,
  },

  // ─── HOUSING (4) ──────────────────────────────────────────────────
  {
    slug: 'pmay-gramin',
    name: 'Pradhan Mantri Awas Yojana - Gramin (PMAY-G)',
    description: 'Financial assistance to rural households for pucca house construction. Rs. 1.20 lakh in plain areas, Rs. 1.30 lakh in hilly states.',
    ministry: 'Ministry of Rural Development',
    state: null, category: 'Housing',
    sourceUrl: 'https://pmayg.nic.in/',
    benefitType: 'monetary', benefitAmount: 120000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [{ field: 'incomeLevel', operator: 'lte', value: 300000, description: 'Annual income below Rs. 3 lakh' }],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit Gram Panchayat and check SECC list', expectedOutcome: 'Eligibility verified' },
      { stepNumber: 2, action: 'Fill application with Panchayat secretary', expectedOutcome: 'Application registered' },
      { stepNumber: 3, action: 'Verification by Block Development Officer', expectedOutcome: 'Approval' },
      { stepNumber: 4, action: 'Funds disbursed in 3 installments via DBT', expectedOutcome: 'Credited at construction milestones' },
    ],
    documents: [D.aadhaar, D.bank, D.domicile, { documentName: 'SECC Verification Slip', description: 'From Gram Panchayat', format: 'Original', required: true }],
    trustScore: 95,
  },
  {
    slug: 'pmay-urban',
    name: 'Pradhan Mantri Awas Yojana - Urban (PMAY-U)',
    description: 'Interest subsidy on home loans (up to Rs. 2.67 lakh) for EWS, LIG, MIG households. Promotes affordable urban housing.',
    ministry: 'Ministry of Housing and Urban Affairs',
    state: null, category: 'Housing',
    sourceUrl: 'https://pmaymis.gov.in/',
    benefitType: 'monetary', benefitAmount: 267000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://pmaymis.gov.in/',
    eligibilityCriteria: [{ field: 'incomeLevel', operator: 'lte', value: 1800000, description: 'Income up to Rs. 18 lakh (varies by category)' }],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit pmaymis.gov.in and select category', expectedOutcome: 'Category selected' },
      { stepNumber: 2, action: 'Fill online form with personal/financial details', expectedOutcome: 'Reference ID generated' },
      { stepNumber: 3, action: 'Bank assesses loan eligibility', expectedOutcome: 'Loan sanctioned' },
      { stepNumber: 4, action: 'Subsidy credited to loan account upfront', expectedOutcome: 'EMIs reduced' },
    ],
    documents: [D.aadhaar, D.pan, D.bank, D.income, { documentName: 'Property Documents', description: 'Sale or builder agreement', format: 'Original', required: true }],
    trustScore: 92,
  },
  {
    slug: 'arhc',
    name: 'Affordable Rental Housing Complexes (ARHC)',
    description: 'Provides dignified rental housing for urban migrants and poor. Existing government-funded vacant houses converted to ARHCs and new units built through PPP.',
    ministry: 'Ministry of Housing and Urban Affairs',
    state: null, category: 'Housing',
    sourceUrl: 'https://arhc.mohua.gov.in/',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://arhc.mohua.gov.in/',
    eligibilityCriteria: [
      { field: 'occupation', operator: 'in', value: ['Salaried', 'Self-Employed', 'Other', 'Unemployed'], description: 'Urban migrant or poor' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply at arhc.mohua.gov.in', expectedOutcome: 'Application submitted' },
      { stepNumber: 2, action: 'Allotment by ULB based on availability', expectedOutcome: 'Rental unit allotted' },
    ],
    documents: [D.aadhaar, { documentName: 'Employment / Migration Proof', description: 'Job letter or migration certificate', format: 'Original', required: false }],
    trustScore: 85,
  },
  {
    slug: 'home-loan-interest',
    name: 'Credit-Linked Subsidy Scheme (CLSS) for Middle Income Group',
    description: 'Interest subsidy of 4% on home loans up to Rs. 9 lakh for MIG-I and 3% on loans up to Rs. 12 lakh for MIG-II households.',
    ministry: 'Ministry of Housing and Urban Affairs',
    state: null, category: 'Housing',
    sourceUrl: 'https://pmaymis.gov.in/',
    benefitType: 'monetary', benefitAmount: 230000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://pmaymis.gov.in/',
    eligibilityCriteria: [{ field: 'incomeLevel', operator: 'between', value: [600000, 1800000], description: 'Annual income Rs. 6-18 lakh' }],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply for home loan at any PLI', expectedOutcome: 'Loan application submitted' },
      { stepNumber: 2, action: 'PLI processes CLSS subsidy', expectedOutcome: 'Subsidy credited' },
    ],
    documents: [D.aadhaar, D.pan, D.income, D.bank],
    trustScore: 90,
  },

  // ─── PENSION (5) ──────────────────────────────────────────────────
  {
    slug: 'atal-pension',
    name: 'Atal Pension Yojana (APY)',
    description: 'Guaranteed minimum pension of Rs. 1,000 to Rs. 5,000 per month after age 60 for unorganized sector workers. Monthly contributions starting at Rs. 42.',
    ministry: 'Ministry of Finance',
    state: null, category: 'Pension',
    sourceUrl: 'https://www.npscra.nsdl.co.in/scheme-details.php',
    benefitType: 'monetary', benefitAmount: 60000, deadline: null,
    applicationMode: 'hybrid', applicationUrl: null,
    eligibilityCriteria: [{ field: 'age', operator: 'between', value: [18, 40], description: 'Age 18-40' }],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit bank or post office', expectedOutcome: 'Form available' },
      { stepNumber: 2, action: 'Fill APY form selecting pension amount', expectedOutcome: 'Form submitted' },
      { stepNumber: 3, action: 'Receive PRAN', expectedOutcome: 'Account active' },
    ],
    documents: [D.aadhaar, D.bank, D.photo],
    trustScore: 92,
  },
  {
    slug: 'indira-gandhi-pension',
    name: 'Indira Gandhi National Old Age Pension Scheme (IGNOAPS)',
    description: 'Monthly pension of Rs. 200 for citizens 60-79 and Rs. 500 for those 80+ from BPL households. State contributions add to base amount.',
    ministry: 'Ministry of Rural Development',
    state: null, category: 'Pension',
    sourceUrl: 'https://nsap.nic.in/',
    benefitType: 'monetary', benefitAmount: 6000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'age', operator: 'gte', value: 60, description: '60+' },
      { field: 'incomeLevel', operator: 'lte', value: 200000, description: 'BPL household' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit Block/Gram Panchayat office', expectedOutcome: 'Officer assigned' },
      { stepNumber: 2, action: 'Submit application with age and BPL proof', expectedOutcome: 'Application registered' },
      { stepNumber: 3, action: 'Pension credited monthly to bank', expectedOutcome: 'Monthly disbursement' },
    ],
    documents: [D.aadhaar, D.bank, { documentName: 'Age Proof', description: 'Birth certificate or school certificate', format: 'Original', required: true }, { documentName: 'BPL Certificate', description: 'BPL ration card or income proof', format: 'Original', required: true }],
    trustScore: 92,
  },
  {
    slug: 'pmvvy',
    name: 'Pradhan Mantri Vaya Vandana Yojana (PMVVY)',
    description: 'Pension scheme for senior citizens 60+ with assured 7.4% return per annum for 10 years. Investment up to Rs. 15 lakh.',
    ministry: 'Ministry of Finance',
    state: null, category: 'Pension',
    sourceUrl: 'https://licindia.in/Products/Pension-Plans/Pradhan-Mantri-Vaya-Vandana-Yojana1',
    benefitType: 'monetary', benefitAmount: 111000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [{ field: 'age', operator: 'gte', value: 60, description: '60 years or older' }],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit any LIC branch', expectedOutcome: 'Form obtained' },
      { stepNumber: 2, action: 'Submit application with KYC', expectedOutcome: 'Form submitted' },
      { stepNumber: 3, action: 'Make lump-sum payment', expectedOutcome: 'Pension begins' },
    ],
    documents: [D.aadhaar, D.pan, D.bank, { documentName: 'Age Proof', description: 'Birth certificate or PAN', format: 'Original', required: true }],
    trustScore: 90,
  },
  {
    slug: 'pm-shram-yogi',
    name: 'Pradhan Mantri Shram Yogi Maan-dhan Yojana (PM-SYM)',
    description: 'Voluntary pension scheme for unorganized workers earning under Rs. 15,000/month. Provides Rs. 3,000/month pension after age 60. Government matches contribution.',
    ministry: 'Ministry of Labour & Employment',
    state: null, category: 'Pension',
    sourceUrl: 'https://maandhan.in/shramyogi',
    benefitType: 'monetary', benefitAmount: 36000, deadline: null,
    applicationMode: 'hybrid', applicationUrl: 'https://maandhan.in/shramyogi',
    eligibilityCriteria: [
      { field: 'age', operator: 'between', value: [18, 40], description: 'Age 18-40' },
      { field: 'incomeLevel', operator: 'lte', value: 180000, description: 'Monthly income up to Rs. 15,000' },
      { field: 'occupation', operator: 'in', value: ['Self-Employed', 'Other', 'Unemployed'], description: 'Unorganized sector worker' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit nearest CSC or maandhan.in', expectedOutcome: 'Application started' },
      { stepNumber: 2, action: 'Submit Aadhaar and bank details', expectedOutcome: 'Account opened' },
      { stepNumber: 3, action: 'Auto-debit set up for monthly contribution', expectedOutcome: 'Pension begins after age 60' },
    ],
    documents: [D.aadhaar, D.bank],
    trustScore: 92,
  },
  {
    slug: 'national-pension-system',
    name: 'National Pension System (NPS)',
    description: 'Voluntary defined-contribution retirement savings scheme open to all citizens. Tax benefits up to Rs. 2 lakh under Sec 80CCD.',
    ministry: 'Ministry of Finance',
    state: null, category: 'Pension',
    sourceUrl: 'https://www.npscra.nsdl.co.in/',
    benefitType: 'monetary', benefitAmount: null, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://enps.nsdl.com/eNPS/NationalPensionSystem.html',
    eligibilityCriteria: [{ field: 'age', operator: 'between', value: [18, 70], description: 'Age 18-70' }],
    applicationSteps: [
      { stepNumber: 1, action: 'Register on enps.nsdl.com or visit POP-SP', expectedOutcome: 'Account opened' },
      { stepNumber: 2, action: 'Make initial contribution (min Rs. 500)', expectedOutcome: 'PRAN issued' },
      { stepNumber: 3, action: 'Make periodic contributions', expectedOutcome: 'Tax benefits and corpus growth' },
    ],
    documents: [D.aadhaar, D.pan, D.bank, D.photo],
    trustScore: 92,
  },

  // ─── FINANCIAL ASSISTANCE (5) ─────────────────────────────────────
  {
    slug: 'jan-dhan',
    name: 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
    description: 'National financial inclusion mission. Includes overdraft up to Rs. 10,000, Rs. 2 lakh accident insurance, Rs. 30,000 life insurance.',
    ministry: 'Ministry of Finance',
    state: null, category: 'Financial Assistance',
    sourceUrl: 'https://pmjdy.gov.in/',
    benefitType: 'non-monetary', benefitAmount: 200000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [{ field: 'age', operator: 'gte', value: 10, description: '10+' }],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit any bank with Aadhaar', expectedOutcome: 'Form available' },
      { stepNumber: 2, action: 'Fill PMJDY account opening form', expectedOutcome: 'Form submitted' },
      { stepNumber: 3, action: 'Receive RuPay debit card and passbook', expectedOutcome: 'Account active' },
    ],
    documents: [D.aadhaar, D.photo],
    trustScore: 95,
  },
  {
    slug: 'pm-jeevan-jyoti',
    name: 'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
    description: 'Life insurance offering Rs. 2 lakh life cover at Rs. 436/year premium. Available to bank account holders aged 18-50.',
    ministry: 'Ministry of Finance',
    state: null, category: 'Financial Assistance',
    sourceUrl: 'https://www.jansuraksha.gov.in/',
    benefitType: 'monetary', benefitAmount: 200000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [{ field: 'age', operator: 'between', value: [18, 50], description: 'Age 18-50' }],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit your bank branch', expectedOutcome: 'Form available' },
      { stepNumber: 2, action: 'Fill PMJJBY consent form', expectedOutcome: 'Form submitted' },
      { stepNumber: 3, action: 'Premium auto-debited annually', expectedOutcome: 'Coverage active' },
    ],
    documents: [D.aadhaar, D.bank],
    trustScore: 95,
  },
  {
    slug: 'pm-suraksha-bima',
    name: 'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
    description: 'Accident insurance providing Rs. 2 lakh for accidental death and Rs. 1 lakh for partial disability at Rs. 20/year premium.',
    ministry: 'Ministry of Finance',
    state: null, category: 'Financial Assistance',
    sourceUrl: 'https://www.jansuraksha.gov.in/',
    benefitType: 'monetary', benefitAmount: 200000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [{ field: 'age', operator: 'between', value: [18, 70], description: 'Age 18-70' }],
    applicationSteps: [
      { stepNumber: 1, action: 'Fill PMSBY consent form at your bank', expectedOutcome: 'Form submitted' },
      { stepNumber: 2, action: 'Rs. 20 auto-debited annually', expectedOutcome: 'Coverage active' },
    ],
    documents: [D.aadhaar, D.bank],
    trustScore: 95,
  },
  {
    slug: 'nbcfdc',
    name: 'National Backward Classes Finance and Development Corporation (NBCFDC)',
    description: 'Provides concessional credit to OBCs for self-employment, skill development, and education. Loans up to Rs. 10 lakh.',
    ministry: 'Ministry of Social Justice and Empowerment',
    state: null, category: 'Financial Assistance',
    sourceUrl: 'https://www.nbcfdc.gov.in/',
    benefitType: 'monetary', benefitAmount: 1000000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'casteCategory', operator: 'eq', value: 'OBC', description: 'OBC category' },
      { field: 'incomeLevel', operator: 'lte', value: 300000, description: 'Family income up to Rs. 3 lakh (non-creamy layer)' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply through State Channelizing Agency', expectedOutcome: 'Application reviewed' },
      { stepNumber: 2, action: 'Loan sanctioned at concessional rate', expectedOutcome: 'Funds disbursed' },
    ],
    documents: [D.aadhaar, D.pan, D.income, D.caste, D.bank],
    trustScore: 88,
  },
  {
    slug: 'nsfdc',
    name: 'National Scheduled Castes Finance and Development Corporation (NSFDC)',
    description: 'Provides concessional credit and skill development to SC families below double the poverty line. Loans up to Rs. 30 lakh.',
    ministry: 'Ministry of Social Justice and Empowerment',
    state: null, category: 'Financial Assistance',
    sourceUrl: 'https://nsfdc.nic.in/',
    benefitType: 'monetary', benefitAmount: 3000000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'casteCategory', operator: 'eq', value: 'SC', description: 'SC category' },
      { field: 'incomeLevel', operator: 'lte', value: 300000, description: 'Below double poverty line' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply through State Channelizing Agency', expectedOutcome: 'Application processed' },
      { stepNumber: 2, action: 'Loan disbursed for project/training', expectedOutcome: 'Funds credited' },
    ],
    documents: [D.aadhaar, D.income, D.caste, D.bank],
    trustScore: 88,
  },
];
