/**
 * Batch 3: Employment, Skill Development, MSME, Startups, State schemes.
 */

import type { SeedScheme } from './seed-data';

const D = {
  aadhaar: { documentName: 'Aadhaar Card', description: '12-digit UIDAI identification', format: 'Original or photocopy', required: true },
  pan: { documentName: 'PAN Card', description: 'Permanent Account Number', format: 'Original', required: true },
  bank: { documentName: 'Bank Account Passbook', description: 'Active bank account', format: 'First page', required: true },
  income: { documentName: 'Income Certificate', description: 'Issued by Tehsildar', format: 'Recent', required: true },
  domicile: { documentName: 'Domicile Proof', description: 'State residence', format: 'Voter ID/utility bill', required: true },
  photo: { documentName: 'Passport-Size Photograph', description: 'Recent', format: 'JPEG/PNG', required: true },
  caste: { documentName: 'Caste Certificate', description: 'For SC/ST/OBC', format: 'From competent authority', required: false },
  bpl: { documentName: 'BPL Certificate', description: 'BPL ration card or proof', format: 'Original', required: true },
  business: { documentName: 'Business Plan / DPR', description: 'Business proposal', format: 'PDF', required: true },
  udyam: { documentName: 'Udyam Registration', description: 'MSME registration', format: 'Online certificate', required: true },
};

export const SCHEMES_BATCH_3: SeedScheme[] = [
  // ─── EMPLOYMENT (8) ───────────────────────────────────────────────
  {
    slug: 'mgnregs',
    name: 'Mahatma Gandhi National Rural Employment Guarantee Scheme (MGNREGS)',
    description: '100 days of guaranteed wage employment per year to rural households. Average daily wage Rs. 220-340 depending on state.',
    ministry: 'Ministry of Rural Development',
    state: null, category: 'Employment',
    sourceUrl: 'https://nrega.nic.in/',
    benefitType: 'monetary', benefitAmount: 30000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [{ field: 'age', operator: 'gte', value: 18, description: '18+' }],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply for Job Card at Gram Panchayat', expectedOutcome: 'Card issued in 15 days' },
      { stepNumber: 2, action: 'Submit work demand application', expectedOutcome: 'Demand registered' },
      { stepNumber: 3, action: 'Receive work allocation in 15 days', expectedOutcome: 'Work assigned' },
      { stepNumber: 4, action: 'Wages paid weekly to bank/post office', expectedOutcome: 'Weekly payment' },
    ],
    documents: [D.aadhaar, D.bank, { documentName: 'Photo ID', description: 'Voter ID/ration card', format: 'Original', required: true }],
    trustScore: 95,
  },
  {
    slug: 'national-career-service',
    name: 'National Career Service (NCS)',
    description: 'Free employment portal connecting job seekers with employers. Provides career counselling, skill development, and government/private job listings.',
    ministry: 'Ministry of Labour & Employment',
    state: null, category: 'Employment',
    sourceUrl: 'https://www.ncs.gov.in/',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://www.ncs.gov.in/',
    eligibilityCriteria: [{ field: 'age', operator: 'gte', value: 14, description: '14+' }],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at ncs.gov.in', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Complete profile with skills/education', expectedOutcome: 'Profile complete' },
      { stepNumber: 3, action: 'Browse jobs and apply', expectedOutcome: 'Applications submitted' },
    ],
    documents: [D.aadhaar],
    trustScore: 88,
  },
  {
    slug: 'pmegp',
    name: 'Prime Minister\'s Employment Generation Programme (PMEGP)',
    description: 'Credit-linked subsidy programme for setting up new micro-enterprises. Subsidy of 15-35% on project cost up to Rs. 50 lakh (manufacturing) / Rs. 20 lakh (service).',
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    state: null, category: 'Employment',
    sourceUrl: 'https://www.kviconline.gov.in/pmegpeportal/',
    benefitType: 'monetary', benefitAmount: 5000000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://www.kviconline.gov.in/pmegpeportal/',
    eligibilityCriteria: [
      { field: 'age', operator: 'gte', value: 18, description: '18+' },
      { field: 'educationLevel', operator: 'in', value: ['Secondary', 'Higher Secondary', 'Graduate', 'Post-Graduate', 'Doctorate'], description: 'Class VIII pass for projects above Rs. 10 lakh (manufacturing)' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register on PMEGP portal', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Submit application with project proposal', expectedOutcome: 'Application reviewed by DLTFC' },
      { stepNumber: 3, action: 'Get bank loan; subsidy released after milestones', expectedOutcome: 'Project funded' },
    ],
    documents: [D.aadhaar, D.pan, D.bank, D.business, D.caste, { documentName: 'Educational Certificate', description: 'Class VIII or above', format: 'Original', required: false }],
    trustScore: 90,
  },
  {
    slug: 'day-nrlm',
    name: 'Deendayal Antyodaya Yojana - National Rural Livelihoods Mission (DAY-NRLM)',
    description: 'Promotes self-employment through Self-Help Groups (SHGs). Provides revolving fund (Rs. 10-15k), training, and bank linkage.',
    ministry: 'Ministry of Rural Development',
    state: null, category: 'Employment',
    sourceUrl: 'https://aajeevika.gov.in/',
    benefitType: 'monetary', benefitAmount: 15000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'incomeLevel', operator: 'lte', value: 300000, description: 'Rural BPL household' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Form/join SHG with Block Mission Management Unit', expectedOutcome: 'SHG registered' },
      { stepNumber: 2, action: 'Receive training and revolving fund', expectedOutcome: 'Capacity built' },
      { stepNumber: 3, action: 'Bank linkage for larger loans', expectedOutcome: 'Credit accessed' },
    ],
    documents: [D.aadhaar, D.bank, D.bpl],
    trustScore: 90,
  },
  {
    slug: 'day-nulm',
    name: 'Deendayal Antyodaya Yojana - National Urban Livelihoods Mission (DAY-NULM)',
    description: 'Provides skill training and self-employment opportunities to urban poor. Loan subsidy of 5-7% interest on loans up to Rs. 2 lakh.',
    ministry: 'Ministry of Housing and Urban Affairs',
    state: null, category: 'Employment',
    sourceUrl: 'https://nulm.gov.in/',
    benefitType: 'monetary', benefitAmount: 200000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'incomeLevel', operator: 'lte', value: 300000, description: 'Urban poor household' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Approach City Mission Management Unit (CMMU)', expectedOutcome: 'Officer assigned' },
      { stepNumber: 2, action: 'Apply for skill training or self-employment loan', expectedOutcome: 'Application processed' },
      { stepNumber: 3, action: 'Receive training certificate or loan', expectedOutcome: 'Benefits delivered' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.domicile],
    trustScore: 88,
  },
  {
    slug: 'apprenticeship-training',
    name: 'National Apprenticeship Promotion Scheme (NAPS)',
    description: 'Provides stipend support to industries to engage apprentices. Stipend of Rs. 1,500-9,000/month based on skill level. Reimburses 25% of stipend (max Rs. 1,500).',
    ministry: 'Ministry of Skill Development and Entrepreneurship',
    state: null, category: 'Employment',
    sourceUrl: 'https://www.apprenticeshipindia.gov.in/',
    benefitType: 'monetary', benefitAmount: 36000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://www.apprenticeshipindia.gov.in/',
    eligibilityCriteria: [
      { field: 'age', operator: 'between', value: [14, 35], description: '14-35' },
      { field: 'educationLevel', operator: 'in', value: ['Secondary', 'Higher Secondary', 'Graduate', 'Post-Graduate', 'Doctorate'], description: 'Class VIII or above' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register on apprenticeshipindia.gov.in', expectedOutcome: 'Profile created' },
      { stepNumber: 2, action: 'Apply to apprenticeship openings', expectedOutcome: 'Industry selects' },
      { stepNumber: 3, action: 'Sign contract and start training', expectedOutcome: 'Apprenticeship begins; stipend paid' },
    ],
    documents: [D.aadhaar, D.bank, { documentName: 'Educational Certificate', description: 'Highest qualification', format: 'Original', required: true }],
    trustScore: 88,
  },
  {
    slug: 'epfo-uan',
    name: 'Universal Account Number (UAN) — EPF Scheme',
    description: 'Mandatory Provident Fund for organized sector employees. 12% employee + 12% employer contribution; 8.25% interest rate.',
    ministry: 'Ministry of Labour & Employment',
    state: null, category: 'Employment',
    sourceUrl: 'https://www.epfindia.gov.in/',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'occupation', operator: 'eq', value: 'Salaried', description: 'Employed in establishment with 20+ employees' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Employer registers you for EPF', expectedOutcome: 'UAN allotted' },
      { stepNumber: 2, action: 'Activate UAN at unifiedportal-mem.epfindia.gov.in', expectedOutcome: 'Online access enabled' },
    ],
    documents: [D.aadhaar, D.pan, D.bank],
    trustScore: 92,
  },
  {
    slug: 'esic',
    name: 'Employees\' State Insurance Scheme (ESIS)',
    description: 'Self-financing social security scheme for organized sector workers earning up to Rs. 21,000/month. Covers medical, sickness, maternity, disablement.',
    ministry: 'Ministry of Labour & Employment',
    state: null, category: 'Employment',
    sourceUrl: 'https://www.esic.gov.in/',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'occupation', operator: 'eq', value: 'Salaried', description: 'Salaried employee in covered establishment' },
      { field: 'incomeLevel', operator: 'lte', value: 252000, description: 'Wages up to Rs. 21,000/month' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Employer registers you under ESIS', expectedOutcome: 'ESIC IP number assigned' },
      { stepNumber: 2, action: 'Receive ESIC card', expectedOutcome: 'Card issued; usable at ESIC dispensaries/hospitals' },
    ],
    documents: [D.aadhaar, D.bank, D.photo],
    trustScore: 92,
  },

  // ─── SKILL DEVELOPMENT (4) ────────────────────────────────────────
  {
    slug: 'pmkvy',
    name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)',
    description: 'Free short-term skill training (200-600 hours) in 250+ job roles across 37 sectors. NSDC certification with placement assistance.',
    ministry: 'Ministry of Skill Development and Entrepreneurship',
    state: null, category: 'Skill Development',
    sourceUrl: 'https://www.pmkvyofficial.org/',
    benefitType: 'non-monetary', benefitAmount: 8000,
    deadline: new Date('2026-12-31'),
    applicationMode: 'online', applicationUrl: 'https://www.pmkvyofficial.org/',
    eligibilityCriteria: [{ field: 'age', operator: 'between', value: [15, 45], description: '15-45' }],
    applicationSteps: [
      { stepNumber: 1, action: 'Find nearest training centre at pmkvyofficial.org', expectedOutcome: 'Centre identified' },
      { stepNumber: 2, action: 'Register and start course', expectedOutcome: 'Enrolled' },
      { stepNumber: 3, action: 'Pass assessment for NSDC certificate', expectedOutcome: 'Certificate issued' },
      { stepNumber: 4, action: 'Receive placement assistance', expectedOutcome: 'Job placement' },
    ],
    documents: [D.aadhaar, D.photo, { documentName: 'Educational Certificate', description: 'Highest qualification', format: 'Original', required: false }],
    trustScore: 90,
  },
  {
    slug: 'deen-dayal-upadhyaya',
    name: 'Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)',
    description: 'Skill training and placement program for rural youth 15-35 from BPL families. Full residential training with 3-month placement guarantee.',
    ministry: 'Ministry of Rural Development',
    state: null, category: 'Skill Development',
    sourceUrl: 'http://ddugky.gov.in/',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'age', operator: 'between', value: [15, 35], description: '15-35' },
      { field: 'incomeLevel', operator: 'lte', value: 250000, description: 'BPL family' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Contact DDU-GKY mobilization team', expectedOutcome: 'Mobilization meeting' },
      { stepNumber: 2, action: 'Choose training course', expectedOutcome: 'Course selected' },
      { stepNumber: 3, action: 'Complete residential training', expectedOutcome: 'Training done' },
      { stepNumber: 4, action: 'Placement support (min 3-month employment)', expectedOutcome: 'Job placed' },
    ],
    documents: [D.aadhaar, D.domicile, D.bpl],
    trustScore: 88,
  },
  {
    slug: 'pm-vishwakarma-skill',
    name: 'PM Vishwakarma Scheme',
    description: 'Supports traditional artisans with skill training, modern toolkits (Rs. 15,000), credit support up to Rs. 3 lakh, and digital transactions incentive.',
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    state: null, category: 'Skill Development',
    sourceUrl: 'https://pmvishwakarma.gov.in/',
    benefitType: 'monetary', benefitAmount: 300000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://pmvishwakarma.gov.in/',
    eligibilityCriteria: [
      { field: 'age', operator: 'gte', value: 18, description: '18+' },
      { field: 'occupation', operator: 'in', value: ['Self-Employed', 'Other'], description: 'Traditional artisan in 18 trades' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at pmvishwakarma.gov.in', expectedOutcome: 'Application submitted' },
      { stepNumber: 2, action: 'Verification at CSC', expectedOutcome: 'Verified' },
      { stepNumber: 3, action: 'Receive ID card and benefits', expectedOutcome: 'All benefits unlocked' },
    ],
    documents: [D.aadhaar, D.bank, D.pan, D.photo],
    trustScore: 92,
  },
  {
    slug: 'ncvet',
    name: 'National Council for Vocational Education and Training (NCVET) — Recognition of Prior Learning',
    description: 'Certifies existing skills of workers without formal training. Free assessment and certification through NSDC-affiliated training partners.',
    ministry: 'Ministry of Skill Development and Entrepreneurship',
    state: null, category: 'Skill Development',
    sourceUrl: 'https://ncvet.gov.in/',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'age', operator: 'gte', value: 18, description: '18+' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Approach NSDC-affiliated training partner', expectedOutcome: 'RPL session scheduled' },
      { stepNumber: 2, action: 'Complete 12-hour orientation and assessment', expectedOutcome: 'Skills recognized' },
      { stepNumber: 3, action: 'Receive NSDC-certified certificate', expectedOutcome: 'Formal recognition' },
    ],
    documents: [D.aadhaar, D.photo],
    trustScore: 85,
  },

  // ─── MSME (5) ─────────────────────────────────────────────────────
  {
    slug: 'mudra-yojana',
    name: 'Pradhan Mantri Mudra Yojana (PMMY)',
    description: 'Loans up to Rs. 10 lakh to non-corporate, non-farm small/micro enterprises. Three categories: Shishu, Kishore, Tarun. No collateral required.',
    ministry: 'Ministry of Finance',
    state: null, category: 'MSME',
    sourceUrl: 'https://www.mudra.org.in/',
    benefitType: 'monetary', benefitAmount: 1000000, deadline: null,
    applicationMode: 'hybrid', applicationUrl: 'https://www.udyamimitra.in/',
    eligibilityCriteria: [
      { field: 'age', operator: 'gte', value: 18, description: '18+' },
      { field: 'occupation', operator: 'in', value: ['Self-Employed', 'Other'], description: 'Small business or entrepreneur' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit udyamimitra.in or bank branch', expectedOutcome: 'Application portal accessed' },
      { stepNumber: 2, action: 'Fill application with business plan', expectedOutcome: 'Form submitted' },
      { stepNumber: 3, action: 'Loan disbursed in 7-15 days of approval', expectedOutcome: 'Funds credited' },
    ],
    documents: [D.aadhaar, D.pan, D.bank, D.business],
    trustScore: 92,
  },
  {
    slug: 'cgtmse',
    name: 'Credit Guarantee Fund for Micro and Small Enterprises (CGTMSE)',
    description: 'Collateral-free credit guarantee for loans up to Rs. 2 crore for micro/small enterprises. Covers 75-85% of loan default.',
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    state: null, category: 'MSME',
    sourceUrl: 'https://www.cgtmse.in/',
    benefitType: 'monetary', benefitAmount: 20000000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'occupation', operator: 'in', value: ['Self-Employed', 'Other'], description: 'Micro/small enterprise' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply for business loan at MLI', expectedOutcome: 'Application submitted' },
      { stepNumber: 2, action: 'MLI applies for CGTMSE coverage', expectedOutcome: 'Coverage applied' },
      { stepNumber: 3, action: 'Loan sanctioned without collateral', expectedOutcome: 'Funds disbursed' },
    ],
    documents: [D.aadhaar, D.pan, D.udyam, { documentName: 'Bank Statements', description: 'Last 6 months', format: 'Original', required: true }],
    trustScore: 90,
  },
  {
    slug: 'udyam',
    name: 'Udyam Registration (MSME Registration)',
    description: 'Free online MSME registration providing recognition, access to government schemes, easy bank loans, and tax benefits. No paperwork required.',
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    state: null, category: 'MSME',
    sourceUrl: 'https://udyamregistration.gov.in/',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://udyamregistration.gov.in/',
    eligibilityCriteria: [
      { field: 'age', operator: 'gte', value: 18, description: '18+' },
      { field: 'occupation', operator: 'in', value: ['Self-Employed', 'Other'], description: 'Existing or new enterprise' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit udyamregistration.gov.in', expectedOutcome: 'Portal accessed' },
      { stepNumber: 2, action: 'Enter Aadhaar and verify via OTP', expectedOutcome: 'Aadhaar verified' },
      { stepNumber: 3, action: 'Fill enterprise details', expectedOutcome: 'Udyam Registration Number issued' },
    ],
    documents: [D.aadhaar, D.pan],
    trustScore: 95,
  },
  {
    slug: 'zed-certification',
    name: 'Zero Defect Zero Effect (ZED) Certification',
    description: 'Certifies MSMEs on quality and environment standards. Provides up to 80% subsidy for certification cost (Rs. 50k-2.5 lakh).',
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    state: null, category: 'MSME',
    sourceUrl: 'https://zed.msme.gov.in/',
    benefitType: 'monetary', benefitAmount: 250000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://zed.msme.gov.in/',
    eligibilityCriteria: [
      { field: 'occupation', operator: 'in', value: ['Self-Employed', 'Other'], description: 'Registered MSME' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register on ZED portal', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Complete self-assessment', expectedOutcome: 'Bronze certified' },
      { stepNumber: 3, action: 'Apply for desk audit / on-site for higher levels', expectedOutcome: 'Silver/Gold certificate' },
    ],
    documents: [D.aadhaar, D.udyam, D.pan],
    trustScore: 88,
  },
  {
    slug: 'msme-tools-room',
    name: 'MSME Tool Room and Technology Centre Scheme',
    description: 'Free/subsidized access to advanced manufacturing tools and training at MSME-DI tool rooms across India. Helps MSMEs upgrade technology.',
    ministry: 'Ministry of Micro, Small and Medium Enterprises',
    state: null, category: 'MSME',
    sourceUrl: 'https://my.msme.gov.in/MyMsme/Reg/COM_TechCentre.aspx',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'occupation', operator: 'in', value: ['Self-Employed', 'Other'], description: 'MSME with valid Udyam registration' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Approach nearest MSME-DI tool room', expectedOutcome: 'Services accessible at concessional rates' },
    ],
    documents: [D.aadhaar, D.udyam],
    trustScore: 85,
  },

  // ─── STARTUPS (4) ─────────────────────────────────────────────────
  {
    slug: 'standup-india',
    name: 'Stand-Up India Scheme',
    description: 'Loans Rs. 10 lakh to Rs. 1 crore to at least one SC/ST and one woman entrepreneur per bank branch for setting up greenfield enterprises.',
    ministry: 'Ministry of Finance',
    state: null, category: 'Startups',
    sourceUrl: 'https://www.standupmitra.in/',
    benefitType: 'monetary', benefitAmount: 10000000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://www.standupmitra.in/',
    eligibilityCriteria: [
      { field: 'age', operator: 'gte', value: 18, description: '18+' },
      { field: 'casteCategory', operator: 'in', value: ['SC', 'ST'], description: 'SC/ST or woman entrepreneur' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at standupmitra.in', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Get linked with handholding agencies', expectedOutcome: 'Business plan ready' },
      { stepNumber: 3, action: 'Apply at scheduled commercial bank', expectedOutcome: 'Application submitted' },
      { stepNumber: 4, action: 'Loan sanctioned for greenfield enterprise', expectedOutcome: 'Funds disbursed' },
    ],
    documents: [D.aadhaar, D.pan, D.caste, D.business],
    trustScore: 92,
  },
  {
    slug: 'startup-india-seed',
    name: 'Startup India Seed Fund Scheme (SISFS)',
    description: 'Up to Rs. 20 lakh as grant for proof of concept and Rs. 50 lakh for commercialization to early-stage DPIIT-recognized startups.',
    ministry: 'Department for Promotion of Industry and Internal Trade',
    state: null, category: 'Startups',
    sourceUrl: 'https://seedfund.startupindia.gov.in/',
    benefitType: 'monetary', benefitAmount: 5000000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://seedfund.startupindia.gov.in/',
    eligibilityCriteria: [
      { field: 'occupation', operator: 'in', value: ['Self-Employed', 'Other'], description: 'DPIIT-recognized startup founder' },
      { field: 'age', operator: 'gte', value: 18, description: '18+' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Get DPIIT recognition at startupindia.gov.in', expectedOutcome: 'Recognition received' },
      { stepNumber: 2, action: 'Apply at seedfund.startupindia.gov.in to incubators', expectedOutcome: 'Application submitted' },
      { stepNumber: 3, action: 'Pitch to selection committee', expectedOutcome: 'Pitch evaluated' },
      { stepNumber: 4, action: 'Receive funds in tranches', expectedOutcome: 'Seed funding received' },
    ],
    documents: [D.aadhaar, D.pan, { documentName: 'DPIIT Recognition', description: 'Startup India recognition', format: 'PDF', required: true }, { documentName: 'Pitch Deck', description: 'Business plan', format: 'PDF', required: true }],
    trustScore: 92,
  },
  {
    slug: 'atal-innovation',
    name: 'Atal Innovation Mission (AIM)',
    description: 'Promotes innovation and entrepreneurship through Atal Tinkering Labs (schools), Atal Incubation Centres (universities), and grant-in-aid up to Rs. 10 crore.',
    ministry: 'NITI Aayog',
    state: null, category: 'Startups',
    sourceUrl: 'https://aim.gov.in/',
    benefitType: 'monetary', benefitAmount: 100000000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://aim.gov.in/',
    eligibilityCriteria: [
      { field: 'age', operator: 'gte', value: 18, description: '18+' },
      { field: 'occupation', operator: 'in', value: ['Self-Employed', 'Other'], description: 'Educational institution / startup' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply through AIM portal during open calls', expectedOutcome: 'Application submitted' },
      { stepNumber: 2, action: 'Selection by AIM committee', expectedOutcome: 'Approval' },
      { stepNumber: 3, action: 'Funds disbursed in tranches', expectedOutcome: 'Project funded' },
    ],
    documents: [D.aadhaar, D.pan, D.business],
    trustScore: 92,
  },
  {
    slug: 'fund-of-funds-startups',
    name: 'Fund of Funds for Startups (FFS)',
    description: 'Rs. 10,000 crore fund managed by SIDBI; invests in SEBI-registered Alternative Investment Funds (AIFs) which then invest in DPIIT-recognized startups.',
    ministry: 'Department for Promotion of Industry and Internal Trade',
    state: null, category: 'Startups',
    sourceUrl: 'https://www.startupindia.gov.in/content/sih/en/government-schemes/fund-of-funds.html',
    benefitType: 'monetary', benefitAmount: 100000000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'occupation', operator: 'in', value: ['Self-Employed', 'Other'], description: 'DPIIT-recognized startup' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Approach AIFs that have received FFS commitments', expectedOutcome: 'Pitch meeting' },
      { stepNumber: 2, action: 'Get equity investment from AIF', expectedOutcome: 'Funds invested' },
    ],
    documents: [D.aadhaar, D.pan, { documentName: 'DPIIT Recognition', description: 'Startup recognition', format: 'PDF', required: true }, D.business],
    trustScore: 90,
  },

  // ─── STATE-SPECIFIC SCHEMES (10) ──────────────────────────────────
  {
    slug: 'tn-amma-two-wheeler',
    name: 'Amma Two-Wheeler Scheme (Tamil Nadu)',
    description: 'Subsidy of Rs. 25,000 (or 50% of cost, whichever is lower) for working women to purchase two-wheelers for commute.',
    ministry: 'Tamil Nadu Social Welfare Department',
    state: 'Tamil Nadu', category: 'Women',
    sourceUrl: 'https://www.tn.gov.in/scheme/data_view/14305',
    benefitType: 'monetary', benefitAmount: 25000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Working woman' },
      { field: 'state', operator: 'eq', value: 'Tamil Nadu', description: 'Tamil Nadu resident' },
      { field: 'incomeLevel', operator: 'lte', value: 250000, description: 'Family income up to Rs. 2.5 lakh' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply at District Social Welfare Office', expectedOutcome: 'Application registered' },
      { stepNumber: 2, action: 'Verification and approval', expectedOutcome: 'Subsidy disbursed to dealer' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.domicile, { documentName: 'Driving License', description: 'Two-wheeler license', format: 'Original', required: true }],
    trustScore: 88,
  },
  {
    slug: 'ka-gruha-lakshmi',
    name: 'Gruha Lakshmi (Karnataka)',
    description: 'Rs. 2,000/month direct cash transfer to woman head of family from BPL/AAY/APL households in Karnataka.',
    ministry: 'Karnataka Department of Women and Child Development',
    state: 'Karnataka', category: 'Women',
    sourceUrl: 'https://gruhalakshmi.karnataka.gov.in/',
    benefitType: 'monetary', benefitAmount: 24000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://sevasindhu.karnataka.gov.in/',
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Woman head of family' },
      { field: 'state', operator: 'eq', value: 'Karnataka', description: 'Karnataka resident' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply at sevasindhu.karnataka.gov.in or Bangalore One', expectedOutcome: 'Application registered' },
      { stepNumber: 2, action: 'Verification of ration card and bank', expectedOutcome: 'Approved' },
      { stepNumber: 3, action: 'Rs. 2,000 credited monthly via DBT', expectedOutcome: 'Monthly cash transfer' },
    ],
    documents: [D.aadhaar, D.bank, { documentName: 'Karnataka Ration Card', description: 'Linked to family head', format: 'Original', required: true }],
    trustScore: 90,
  },
  {
    slug: 'ts-rythu-bandhu',
    name: 'Rythu Bandhu (Telangana)',
    description: 'Investment support of Rs. 10,000/acre/year (Rs. 5,000 per crop season) directly to all farm-owning farmers in Telangana.',
    ministry: 'Telangana Department of Agriculture',
    state: 'Telangana', category: 'Agriculture',
    sourceUrl: 'https://rythubandhu.telangana.gov.in/',
    benefitType: 'monetary', benefitAmount: 10000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'occupation', operator: 'eq', value: 'Farmer', description: 'Farm-owning farmer in Telangana' },
      { field: 'state', operator: 'eq', value: 'Telangana', description: 'Telangana resident' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Auto-enrolled based on land records', expectedOutcome: 'Eligibility determined' },
      { stepNumber: 2, action: 'Cheque distributed at village level or DBT', expectedOutcome: 'Twice-yearly disbursement' },
    ],
    documents: [D.aadhaar, D.bank, { documentName: 'Pattadar Passbook', description: 'Telangana land record', format: 'Original', required: true }],
    trustScore: 90,
  },
  {
    slug: 'mh-ladki-bahin',
    name: 'Mukhyamantri Majhi Ladki Bahin Yojana (Maharashtra)',
    description: 'Rs. 1,500/month direct benefit to women aged 21-65 from Maharashtra families with annual income up to Rs. 2.5 lakh.',
    ministry: 'Maharashtra Department of Women and Child Development',
    state: 'Maharashtra', category: 'Women',
    sourceUrl: 'https://ladakibahin.maharashtra.gov.in/',
    benefitType: 'monetary', benefitAmount: 18000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://ladakibahin.maharashtra.gov.in/',
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Woman' },
      { field: 'age', operator: 'between', value: [21, 65], description: 'Age 21-65' },
      { field: 'state', operator: 'eq', value: 'Maharashtra', description: 'Maharashtra resident' },
      { field: 'incomeLevel', operator: 'lte', value: 250000, description: 'Family income up to Rs. 2.5 lakh' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply on Nari Shakti Doot app or Aaple Sarkar portal', expectedOutcome: 'Application submitted' },
      { stepNumber: 2, action: 'Verification of documents', expectedOutcome: 'Approved' },
      { stepNumber: 3, action: 'Rs. 1,500 monthly via DBT', expectedOutcome: 'Monthly transfer' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.domicile],
    trustScore: 90,
  },
  {
    slug: 'mp-ladli-behna',
    name: 'Mukhyamantri Ladli Behna Yojana (Madhya Pradesh)',
    description: 'Rs. 1,250/month direct benefit to married women aged 21-60 from MP families with annual income up to Rs. 2.5 lakh.',
    ministry: 'Madhya Pradesh Women and Child Development',
    state: 'Madhya Pradesh', category: 'Women',
    sourceUrl: 'https://cmladlibahna.mp.gov.in/',
    benefitType: 'monetary', benefitAmount: 15000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Married woman' },
      { field: 'age', operator: 'between', value: [21, 60], description: 'Age 21-60' },
      { field: 'state', operator: 'eq', value: 'Madhya Pradesh', description: 'MP resident' },
      { field: 'maritalStatus', operator: 'in', value: ['Married', 'Widowed', 'Divorced'], description: 'Married/widowed/divorced' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit Gram Panchayat / ward office camp', expectedOutcome: 'Application registered' },
      { stepNumber: 2, action: 'Verification', expectedOutcome: 'Approved' },
      { stepNumber: 3, action: 'Rs. 1,250 monthly via DBT', expectedOutcome: 'Monthly disbursement' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.domicile],
    trustScore: 90,
  },
  {
    slug: 'wb-lakshmir-bhandar',
    name: 'Lakshmir Bhandar (West Bengal)',
    description: 'Monthly cash assistance of Rs. 1,000 (general) or Rs. 1,200 (SC/ST) to women aged 25-60 in West Bengal.',
    ministry: 'West Bengal Department of Women and Child Development',
    state: 'West Bengal', category: 'Women',
    sourceUrl: 'https://socialsecurity.wb.gov.in/',
    benefitType: 'monetary', benefitAmount: 14400, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Woman' },
      { field: 'age', operator: 'between', value: [25, 60], description: 'Age 25-60' },
      { field: 'state', operator: 'eq', value: 'West Bengal', description: 'WB resident' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply at Duare Sarkar camps', expectedOutcome: 'Application registered' },
      { stepNumber: 2, action: 'Verification', expectedOutcome: 'Approved' },
      { stepNumber: 3, action: 'Monthly DBT', expectedOutcome: 'Monthly transfer' },
    ],
    documents: [D.aadhaar, D.bank, { documentName: 'Swasthya Sathi Card', description: 'WB health card', format: 'Original', required: true }],
    trustScore: 90,
  },
  {
    slug: 'up-kanya-sumangala',
    name: 'Mukhyamantri Kanya Sumangala Yojana (Uttar Pradesh)',
    description: 'Total Rs. 25,000 in 6 installments to girl child in UP — at birth, after 1st year vaccinations, school enrollment milestones.',
    ministry: 'Uttar Pradesh Department of Women Welfare',
    state: 'Uttar Pradesh', category: 'Women',
    sourceUrl: 'https://mksy.up.gov.in/',
    benefitType: 'monetary', benefitAmount: 25000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://mksy.up.gov.in/',
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Girl child' },
      { field: 'state', operator: 'eq', value: 'Uttar Pradesh', description: 'UP resident' },
      { field: 'incomeLevel', operator: 'lte', value: 300000, description: 'Family income up to Rs. 3 lakh' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register on mksy.up.gov.in', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Submit form with documents', expectedOutcome: 'Application registered' },
      { stepNumber: 3, action: 'Verification by Mahila Welfare officer', expectedOutcome: 'Approved' },
      { stepNumber: 4, action: 'Installments credited as milestones met', expectedOutcome: 'Cash credited' },
    ],
    documents: [D.aadhaar, D.bank, { documentName: 'Birth Certificate (girl child)', description: 'Mandatory', format: 'Original', required: true }, D.income, D.domicile],
    trustScore: 88,
  },
  {
    slug: 'rj-indira-smartphone',
    name: 'Indira Gandhi Smartphone Scheme (Rajasthan)',
    description: 'Free smartphone with 3-year internet connectivity to women heads of Chiranjeevi family beneficiaries in Rajasthan.',
    ministry: 'Rajasthan Department of Information Technology',
    state: 'Rajasthan', category: 'Women',
    sourceUrl: 'https://igsy.rajasthan.gov.in/',
    benefitType: 'non-monetary', benefitAmount: 12000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Woman head of family' },
      { field: 'state', operator: 'eq', value: 'Rajasthan', description: 'Rajasthan resident' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit distribution camp announced by district', expectedOutcome: 'Slot allocated' },
      { stepNumber: 2, action: 'Verify Chiranjeevi card', expectedOutcome: 'Verified' },
      { stepNumber: 3, action: 'Receive smartphone with SIM', expectedOutcome: 'Smartphone distributed' },
    ],
    documents: [D.aadhaar, { documentName: 'Chiranjeevi Card', description: 'Rajasthan health insurance card', format: 'Original', required: true }, { documentName: 'Jan Aadhaar Card', description: 'Rajasthan family ID', format: 'Original', required: true }],
    trustScore: 88,
  },
  {
    slug: 'gj-vahli-dikri',
    name: 'Vahli Dikri Yojana (Gujarat)',
    description: 'Total Rs. 1.10 lakh in installments — Rs. 4,000 in Class 1, Rs. 6,000 in Class 9, Rs. 1 lakh on turning 18 — for first/second girl child in Gujarat families.',
    ministry: 'Gujarat Department of Women and Child Development',
    state: 'Gujarat', category: 'Women',
    sourceUrl: 'https://wcd.gujarat.gov.in/',
    benefitType: 'monetary', benefitAmount: 110000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Girl child (1st or 2nd)' },
      { field: 'state', operator: 'eq', value: 'Gujarat', description: 'Gujarat resident' },
      { field: 'incomeLevel', operator: 'lte', value: 200000, description: 'Family income up to Rs. 2 lakh' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at Anganwadi within 1 year of birth', expectedOutcome: 'Registered' },
      { stepNumber: 2, action: 'Installments credited as milestones met', expectedOutcome: 'Cash credited' },
    ],
    documents: [D.aadhaar, D.bank, { documentName: 'Girl Child Birth Certificate', description: 'Mandatory', format: 'Original', required: true }, D.income],
    trustScore: 88,
  },
  {
    slug: 'dl-mukhyamantri-tirth',
    name: 'Mukhyamantri Tirth Yatra Yojana (Delhi)',
    description: 'Free pilgrimage to senior citizens of Delhi (60+ years) to various religious destinations including Mathura, Vaishno Devi, Tirupati, Shirdi, Ajmer.',
    ministry: 'Delhi Department of Revenue',
    state: 'Delhi', category: 'Pension',
    sourceUrl: 'https://edistrict.delhigovt.nic.in/',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://edistrict.delhigovt.nic.in/',
    eligibilityCriteria: [
      { field: 'age', operator: 'gte', value: 60, description: '60+' },
      { field: 'state', operator: 'eq', value: 'Delhi', description: 'Delhi resident' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply at edistrict.delhigovt.nic.in', expectedOutcome: 'Application submitted' },
      { stepNumber: 2, action: 'Verification by SDM', expectedOutcome: 'Selected' },
      { stepNumber: 3, action: 'Travel as per allotted batch', expectedOutcome: 'Free pilgrimage' },
    ],
    documents: [D.aadhaar, D.domicile, { documentName: 'Age Proof', description: 'Birth/PAN/voter ID', format: 'Original', required: true }],
    trustScore: 88,
  },
];
