/**
 * Batch 4: Additional schemes — minorities, disabled, more state schemes,
 * more education schemes to push total over 100.
 */

import type { SeedScheme } from './seed-data';

const D = {
  aadhaar: { documentName: 'Aadhaar Card', description: '12-digit UIDAI identification', format: 'Original or photocopy', required: true },
  pan: { documentName: 'PAN Card', description: 'Permanent Account Number', format: 'Original', required: true },
  bank: { documentName: 'Bank Account Passbook', description: 'Active bank account', format: 'First page', required: true },
  income: { documentName: 'Income Certificate', description: 'Issued by Tehsildar', format: 'Recent', required: true },
  domicile: { documentName: 'Domicile Proof', description: 'State residence', format: 'Voter ID/utility bill', required: true },
  photo: { documentName: 'Passport-Size Photograph', description: 'Recent', format: 'JPEG/PNG', required: true },
  caste: { documentName: 'Caste Certificate', description: 'For SC/ST/OBC', format: 'Original', required: false },
  bpl: { documentName: 'BPL Certificate', description: 'BPL ration card or proof', format: 'Original', required: true },
  marksheet: { documentName: 'Latest Mark Sheet', description: 'Most recent academic record', format: 'Original', required: true },
  bonafide: { documentName: 'Bonafide Certificate', description: 'From educational institution', format: 'Original', required: true },
  disability: { documentName: 'Disability Certificate', description: 'From competent medical authority (40%+)', format: 'Original', required: true },
};

export const SCHEMES_BATCH_4: SeedScheme[] = [
  // ─── MINORITIES & DISABLED (5) ────────────────────────────────────
  {
    slug: 'pre-matric-minorities',
    name: 'Pre-Matric Scholarship for Minorities',
    description: 'Scholarship to students from notified minority communities (Muslim, Christian, Sikh, Buddhist, Jain, Parsi) studying in Class I-X. Amount: Rs. 1,000 to Rs. 10,700 per year.',
    ministry: 'Ministry of Minority Affairs',
    state: null, category: 'Scholarships',
    sourceUrl: 'https://scholarships.gov.in/',
    benefitType: 'monetary', benefitAmount: 10700,
    deadline: new Date('2026-10-31'),
    applicationMode: 'online', applicationUrl: 'https://scholarships.gov.in/',
    eligibilityCriteria: [
      { field: 'incomeLevel', operator: 'lte', value: 100000, description: 'Family income up to Rs. 1 lakh' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at scholarships.gov.in', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Fill form and upload documents', expectedOutcome: 'Application submitted' },
      { stepNumber: 3, action: 'Institute verifies and approves', expectedOutcome: 'Scholarship credited' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.marksheet, { documentName: 'Minority Community Certificate', description: 'Self-declaration', format: 'Original', required: true }],
    trustScore: 90,
  },
  {
    slug: 'post-matric-minorities',
    name: 'Post-Matric Scholarship for Minorities',
    description: 'Scholarship to minority students in Class XI to PhD. Amount: Rs. 230 to Rs. 1,200 per month plus admission/tuition fees.',
    ministry: 'Ministry of Minority Affairs',
    state: null, category: 'Scholarships',
    sourceUrl: 'https://scholarships.gov.in/',
    benefitType: 'monetary', benefitAmount: 14400,
    deadline: new Date('2026-10-31'),
    applicationMode: 'online', applicationUrl: 'https://scholarships.gov.in/',
    eligibilityCriteria: [
      { field: 'incomeLevel', operator: 'lte', value: 200000, description: 'Family income up to Rs. 2 lakh' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at scholarships.gov.in', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Fill form with academic details', expectedOutcome: 'Submitted' },
      { stepNumber: 3, action: 'Verified and credited via DBT', expectedOutcome: 'Funds received' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.marksheet, D.bonafide, { documentName: 'Minority Community Self-Declaration', description: 'Self-attested', format: 'Original', required: true }],
    trustScore: 90,
  },
  {
    slug: 'national-fellowship-disabled',
    name: 'National Fellowship for Persons with Disabilities (NFPwD)',
    description: 'Fellowship of Rs. 31,000 (JRF) and Rs. 35,000 (SRF) per month for MPhil/PhD scholars with disabilities (40%+).',
    ministry: 'Department of Empowerment of Persons with Disabilities',
    state: null, category: 'Scholarships',
    sourceUrl: 'https://disabilityaffairs.gov.in/',
    benefitType: 'monetary', benefitAmount: 372000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://www.ugc.gov.in/',
    eligibilityCriteria: [
      { field: 'disabilityStatus', operator: 'eq', value: true, description: '40%+ disability' },
      { field: 'educationLevel', operator: 'in', value: ['Post-Graduate', 'Doctorate'], description: 'MPhil/PhD candidate' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply through UGC portal', expectedOutcome: 'Application submitted' },
      { stepNumber: 2, action: 'Selection by UGC committee', expectedOutcome: 'Fellowship awarded' },
    ],
    documents: [D.aadhaar, D.bank, D.disability, D.marksheet, D.bonafide],
    trustScore: 90,
  },
  {
    slug: 'unique-disability-id',
    name: 'Unique Disability Identity (UDID) Card',
    description: 'Single document of identity, verification of disability and benefits. Enables easier access to all disability-related government schemes.',
    ministry: 'Department of Empowerment of Persons with Disabilities',
    state: null, category: 'Financial Assistance',
    sourceUrl: 'https://www.swavlambancard.gov.in/',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://www.swavlambancard.gov.in/',
    eligibilityCriteria: [
      { field: 'disabilityStatus', operator: 'eq', value: true, description: 'Person with disability' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at swavlambancard.gov.in', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Upload documents and disability certificate', expectedOutcome: 'Application submitted' },
      { stepNumber: 3, action: 'Verification by CMO/civil surgeon', expectedOutcome: 'UDID Card issued' },
    ],
    documents: [D.aadhaar, D.disability, D.photo],
    trustScore: 92,
  },
  {
    slug: 'aids-prosthetic',
    name: 'Assistance to Disabled Persons (ADIP) Scheme',
    description: 'Provides aids and assistive devices (wheelchairs, hearing aids, prosthetics) free of cost to persons with disabilities below specified income limits.',
    ministry: 'Department of Empowerment of Persons with Disabilities',
    state: null, category: 'Financial Assistance',
    sourceUrl: 'https://disabilityaffairs.gov.in/content/page/adip-scheme.php',
    benefitType: 'non-monetary', benefitAmount: 50000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'disabilityStatus', operator: 'eq', value: true, description: '40%+ disability' },
      { field: 'incomeLevel', operator: 'lte', value: 250000, description: 'Family income up to Rs. 2.5 lakh' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit Block Development Office or ALIMCO', expectedOutcome: 'Application submitted' },
      { stepNumber: 2, action: 'Medical assessment for required device', expectedOutcome: 'Device specified' },
      { stepNumber: 3, action: 'Receive aid free of cost', expectedOutcome: 'Device delivered' },
    ],
    documents: [D.aadhaar, D.disability, D.income],
    trustScore: 88,
  },

  // ─── CONSUMER / WELFARE (5) ───────────────────────────────────────
  {
    slug: 'antyodaya-anna',
    name: 'Antyodaya Anna Yojana (AAY)',
    description: 'Provides 35 kg of foodgrains per family per month at subsidised rates of Rs. 2/kg wheat and Rs. 3/kg rice to poorest of poor families.',
    ministry: 'Ministry of Consumer Affairs, Food and Public Distribution',
    state: null, category: 'Financial Assistance',
    sourceUrl: 'https://nfsa.gov.in/',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'incomeLevel', operator: 'lte', value: 100000, description: 'Poorest of poor (AAY criteria)' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply at District Food and Civil Supplies Office', expectedOutcome: 'Application registered' },
      { stepNumber: 2, action: 'Verification by SDM', expectedOutcome: 'AAY ration card issued' },
      { stepNumber: 3, action: 'Buy grains at subsidized rates from FPS', expectedOutcome: 'Monthly entitlement' },
    ],
    documents: [D.aadhaar, D.income, D.domicile],
    trustScore: 92,
  },
  {
    slug: 'one-nation-one-ration',
    name: 'One Nation One Ration Card (ONORC)',
    description: 'Allows ration card holders to lift their entitled foodgrains from any Fair Price Shop across India through portability of ration cards.',
    ministry: 'Ministry of Consumer Affairs, Food and Public Distribution',
    state: null, category: 'Financial Assistance',
    sourceUrl: 'https://nfsa.gov.in/portal/onorc-mera-ration-app',
    benefitType: 'non-monetary', benefitAmount: null, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'incomeLevel', operator: 'lte', value: 200000, description: 'Existing ration card holder (AAY/PHH)' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Ensure ration card seeded with Aadhaar', expectedOutcome: 'Aadhaar linked' },
      { stepNumber: 2, action: 'Visit any FPS in any state', expectedOutcome: 'Lift grains via biometric verification' },
    ],
    documents: [{ documentName: 'Existing Ration Card', description: 'AAY/PHH card', format: 'Original', required: true }, D.aadhaar],
    trustScore: 95,
  },
  {
    slug: 'free-kerosene',
    name: 'Direct Benefit Transfer for LPG (PAHAL)',
    description: 'Subsidy on LPG cylinders directly transferred to bank account of consumer. Simplifies subsidy delivery and prevents leakage.',
    ministry: 'Ministry of Petroleum and Natural Gas',
    state: null, category: 'Financial Assistance',
    sourceUrl: 'https://pahal.petroleum.gov.in/',
    benefitType: 'monetary', benefitAmount: 200, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'age', operator: 'gte', value: 18, description: 'LPG consumer with valid connection' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Link Aadhaar with LPG connection at distributor', expectedOutcome: 'Aadhaar linked' },
      { stepNumber: 2, action: 'Subsidy auto-credited on each cylinder purchase', expectedOutcome: 'DBT to bank account' },
    ],
    documents: [D.aadhaar, D.bank, { documentName: 'LPG Consumer Number', description: 'From distributor', format: 'Original', required: true }],
    trustScore: 95,
  },
  {
    slug: 'national-social-assistance',
    name: 'National Social Assistance Programme (NSAP) - Disabled Pension',
    description: 'Monthly pension of Rs. 300-500 to persons with severe disabilities (80%+) from BPL households.',
    ministry: 'Ministry of Rural Development',
    state: null, category: 'Pension',
    sourceUrl: 'https://nsap.nic.in/',
    benefitType: 'monetary', benefitAmount: 6000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'disabilityStatus', operator: 'eq', value: true, description: '80%+ severe disability' },
      { field: 'age', operator: 'between', value: [18, 79], description: 'Age 18-79' },
      { field: 'incomeLevel', operator: 'lte', value: 200000, description: 'BPL household' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit Block Development Office or Gram Panchayat', expectedOutcome: 'Officer assigned' },
      { stepNumber: 2, action: 'Submit application with disability and BPL proof', expectedOutcome: 'Application registered' },
      { stepNumber: 3, action: 'Pension credited monthly', expectedOutcome: 'Monthly DBT' },
    ],
    documents: [D.aadhaar, D.bank, D.disability, D.bpl],
    trustScore: 90,
  },
  {
    slug: 'widow-pension',
    name: 'Indira Gandhi National Widow Pension Scheme (IGNWPS)',
    description: 'Monthly pension of Rs. 300-500 to BPL widows aged 40-79 years to provide financial support.',
    ministry: 'Ministry of Rural Development',
    state: null, category: 'Pension',
    sourceUrl: 'https://nsap.nic.in/',
    benefitType: 'monetary', benefitAmount: 6000, deadline: null,
    applicationMode: 'offline', applicationUrl: null,
    eligibilityCriteria: [
      { field: 'gender', operator: 'eq', value: 'Female', description: 'Widow' },
      { field: 'maritalStatus', operator: 'eq', value: 'Widowed', description: 'Widowed' },
      { field: 'age', operator: 'between', value: [40, 79], description: '40-79' },
      { field: 'incomeLevel', operator: 'lte', value: 200000, description: 'BPL household' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Visit Block Development Office', expectedOutcome: 'Officer assigned' },
      { stepNumber: 2, action: 'Submit application with widow certificate and BPL', expectedOutcome: 'Application registered' },
      { stepNumber: 3, action: 'Pension credited monthly', expectedOutcome: 'Monthly DBT' },
    ],
    documents: [D.aadhaar, D.bank, { documentName: 'Husband\'s Death Certificate', description: 'Issued by competent authority', format: 'Original', required: true }, D.bpl],
    trustScore: 90,
  },

  // ─── EDUCATION ADDITIONAL (5) ─────────────────────────────────────
  {
    slug: 'scholarship-sc-students',
    name: 'Post-Matric Scholarship for Scheduled Castes Students',
    description: 'Provides scholarship to SC students for post-matriculation studies. Covers tuition fees, maintenance allowance, and study tour charges.',
    ministry: 'Ministry of Social Justice and Empowerment',
    state: null, category: 'Scholarships',
    sourceUrl: 'https://scholarships.gov.in/',
    benefitType: 'monetary', benefitAmount: 25000,
    deadline: new Date('2026-10-31'),
    applicationMode: 'online', applicationUrl: 'https://scholarships.gov.in/',
    eligibilityCriteria: [
      { field: 'casteCategory', operator: 'eq', value: 'SC', description: 'SC category' },
      { field: 'incomeLevel', operator: 'lte', value: 250000, description: 'Family income up to Rs. 2.5 lakh' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at scholarships.gov.in', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Fill application with caste and income proof', expectedOutcome: 'Submitted' },
      { stepNumber: 3, action: 'Institute and authority verify', expectedOutcome: 'Scholarship credited' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.caste, D.marksheet, D.bonafide],
    trustScore: 92,
  },
  {
    slug: 'scholarship-st-students',
    name: 'Post-Matric Scholarship for Scheduled Tribes Students',
    description: 'Scholarship for ST students for post-matriculation studies. Covers tuition fees, maintenance allowance, and reader allowance.',
    ministry: 'Ministry of Tribal Affairs',
    state: null, category: 'Scholarships',
    sourceUrl: 'https://scholarships.gov.in/',
    benefitType: 'monetary', benefitAmount: 25000,
    deadline: new Date('2026-10-31'),
    applicationMode: 'online', applicationUrl: 'https://scholarships.gov.in/',
    eligibilityCriteria: [
      { field: 'casteCategory', operator: 'eq', value: 'ST', description: 'ST category' },
      { field: 'incomeLevel', operator: 'lte', value: 250000, description: 'Family income up to Rs. 2.5 lakh' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Register at scholarships.gov.in', expectedOutcome: 'Account created' },
      { stepNumber: 2, action: 'Fill application with caste/income proof', expectedOutcome: 'Submitted' },
      { stepNumber: 3, action: 'Verified and disbursed via DBT', expectedOutcome: 'Funds received' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.caste, D.marksheet, D.bonafide],
    trustScore: 92,
  },
  {
    slug: 'national-overseas-scholarship',
    name: 'National Overseas Scholarship for SC',
    description: 'Provides financial assistance to selected students from SC, denotified, nomadic and semi-nomadic tribes for pursuing Master\'s and PhD programs abroad.',
    ministry: 'Ministry of Social Justice and Empowerment',
    state: null, category: 'Scholarships',
    sourceUrl: 'https://nosmsje.gov.in/',
    benefitType: 'monetary', benefitAmount: 1500000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://nosmsje.gov.in/',
    eligibilityCriteria: [
      { field: 'casteCategory', operator: 'eq', value: 'SC', description: 'SC, denotified, nomadic, semi-nomadic tribes' },
      { field: 'incomeLevel', operator: 'lte', value: 800000, description: 'Family income up to Rs. 8 lakh' },
      { field: 'age', operator: 'lte', value: 35, description: 'Up to 35 years' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply at nosmsje.gov.in', expectedOutcome: 'Application submitted' },
      { stepNumber: 2, action: 'Selection based on academic merit', expectedOutcome: 'Selected' },
      { stepNumber: 3, action: 'Funds disbursed for tuition, living, travel', expectedOutcome: 'Studies abroad funded' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.caste, D.marksheet, { documentName: 'Admission Letter from Foreign University', description: 'For Masters/PhD', format: 'Original', required: true }],
    trustScore: 92,
  },
  {
    slug: 'maulana-azad-fellowship',
    name: 'Maulana Azad National Fellowship (MANF)',
    description: 'Fellowship of Rs. 31,000 (JRF) and Rs. 35,000 (SRF) per month for MPhil/PhD students from notified minority communities.',
    ministry: 'Ministry of Minority Affairs',
    state: null, category: 'Scholarships',
    sourceUrl: 'https://www.ugc.gov.in/page/Maulana-Azad-National-Fellowship.aspx',
    benefitType: 'monetary', benefitAmount: 372000, deadline: null,
    applicationMode: 'online', applicationUrl: 'https://www.ugc.gov.in/',
    eligibilityCriteria: [
      { field: 'incomeLevel', operator: 'lte', value: 600000, description: 'Family income up to Rs. 6 lakh' },
      { field: 'educationLevel', operator: 'in', value: ['Post-Graduate', 'Doctorate'], description: 'MPhil/PhD' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Apply through UGC NET portal', expectedOutcome: 'Application submitted' },
      { stepNumber: 2, action: 'Clear NET; selection on merit + minority status', expectedOutcome: 'Selected' },
      { stepNumber: 3, action: 'Fellowship credited monthly', expectedOutcome: 'Monthly stipend' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.marksheet, { documentName: 'Minority Community Certificate', description: 'Self-declaration', format: 'Original', required: true }],
    trustScore: 90,
  },
  {
    slug: 'national-means-merit',
    name: 'National Means-cum-Merit Scholarship Scheme (NMMSS)',
    description: 'Scholarship of Rs. 12,000 per year (Class IX-XII) to meritorious students from economically weaker sections to prevent dropout at upper primary stage.',
    ministry: 'Ministry of Education',
    state: null, category: 'Scholarships',
    sourceUrl: 'https://scholarships.gov.in/',
    benefitType: 'monetary', benefitAmount: 12000,
    deadline: new Date('2026-10-31'),
    applicationMode: 'online', applicationUrl: 'https://scholarships.gov.in/',
    eligibilityCriteria: [
      { field: 'incomeLevel', operator: 'lte', value: 350000, description: 'Family income up to Rs. 3.5 lakh' },
      { field: 'age', operator: 'between', value: [13, 18], description: 'Class IX-XII students' },
    ],
    applicationSteps: [
      { stepNumber: 1, action: 'Take state-level NMMS test in Class VIII', expectedOutcome: 'Qualified' },
      { stepNumber: 2, action: 'Register at scholarships.gov.in', expectedOutcome: 'Account created' },
      { stepNumber: 3, action: 'Submit form annually for renewal', expectedOutcome: 'Annual scholarship credited' },
    ],
    documents: [D.aadhaar, D.bank, D.income, D.marksheet, D.bonafide],
    trustScore: 90,
  },
];
