/**
 * Storage abstraction for Scheme_Assistant query / response logs.
 *
 * Two implementations live in this file:
 *   - {@link InMemoryAIQueryLogStore} — used by tests and any hermetic
 *     (e.g. local dev without Postgres) workflow.
 *   - {@link PrismaAIQueryLogStore} — production wiring backed by the
 *     `assistant_query_logs` table introduced in the 0003 migration.
 *
 * Both implementations honour the 90-day retention contract from
 * Req 21.1 via {@link AIQueryLogStore.pruneOlderThan}, which the worker
 * scheduler invokes daily.
 *
 * Validates: Requirements 21.1, 21.5.
 */

import { randomUUID } from 'node:crypto';

import { QUERY_LOG_RETENTION_MS } from './constants';
import type { AIQueryLog } from './types';

// ─── Public store interface ──────────────────────────────────────────────────

/** Optional filter applied when listing logs. */
export interface ListLogsFilter {
  userId?: string;
  sessionId?: string;
  /** Only return logs created on or after this date (inclusive). */
  since?: Date;
  /** Only return logs created before this date (exclusive). */
  before?: Date;
  /** Cap on returned rows. Implementations may impose a hard upper bound. */
  limit?: number;
}

export interface AIQueryLogStore {
  /**
   * Persist a single log entry. The `id` is generated by the store so
   * callers don't have to thread UUIDs through the assistant pipeline.
   */
  append(entry: Omit<AIQueryLog, 'id'>): Promise<AIQueryLog>;
  /** Look up a log row by its persisted id. */
  findById(id: string): Promise<AIQueryLog | null>;
  /** Look up a log row by trace id (the more common admin query). */
  findByTraceId(traceId: string): Promise<AIQueryLog | null>;
  /** List logs matching a filter, newest-first. */
  list(filter?: ListLogsFilter): Promise<AIQueryLog[]>;
  /**
   * Delete every log row whose `createdAt` is strictly older than
   * `cutoff`. Returns the number of rows removed so the worker can log
   * its sweep.
   */
  pruneOlderThan(cutoff: Date): Promise<number>;
}

/**
 * Default cutoff used when callers don't pass an explicit one — exposed
 * so the worker's logs can show "pruning entries older than X".
 */
export function retentionCutoff(now: Date = new Date()): Date {
  return new Date(now.getTime() - QUERY_LOG_RETENTION_MS);
}

// ─── In-memory implementation ────────────────────────────────────────────────

export class InMemoryAIQueryLogStore implements AIQueryLogStore {
  private readonly rows = new Map<string, AIQueryLog>();

  async append(entry: Omit<AIQueryLog, 'id'>): Promise<AIQueryLog> {
    const id = randomUUID();
    const row: AIQueryLog = {
      ...entry,
      id,
      // Defensive copies so callers can mutate their own arrays freely.
      retrievedChunks: entry.retrievedChunks.map((c) => ({ ...c })),
      sources: entry.sources.map((s) => ({ ...s })),
    };
    this.rows.set(id, row);
    return row;
  }

  async findById(id: string): Promise<AIQueryLog | null> {
    return this.rows.get(id) ?? null;
  }

  async findByTraceId(traceId: string): Promise<AIQueryLog | null> {
    for (const row of this.rows.values()) {
      if (row.traceId === traceId) return row;
    }
    return null;
  }

  async list(filter: ListLogsFilter = {}): Promise<AIQueryLog[]> {
    const out: AIQueryLog[] = [];
    for (const row of this.rows.values()) {
      if (filter.userId !== undefined && row.userId !== filter.userId) continue;
      if (filter.sessionId !== undefined && row.sessionId !== filter.sessionId) continue;
      if (filter.since !== undefined && row.createdAt < filter.since) continue;
      if (filter.before !== undefined && row.createdAt >= filter.before) continue;
      out.push(row);
    }
    out.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
    if (typeof filter.limit === 'number' && filter.limit >= 0) {
      return out.slice(0, filter.limit);
    }
    return out;
  }

  async pruneOlderThan(cutoff: Date): Promise<number> {
    let removed = 0;
    for (const [id, row] of this.rows) {
      if (row.createdAt < cutoff) {
        this.rows.delete(id);
        removed += 1;
      }
    }
    return removed;
  }

  /** Test helper: total rows currently stored. */
  get size(): number {
    return this.rows.size;
  }
}

// ─── Prisma-backed implementation ────────────────────────────────────────────

/**
 * Narrow subset of the Prisma client we depend on. Decouples the store
 * from the generated types so the file compiles cleanly even before a
 * `prisma generate` has run for the new model.
 */
export interface AIQueryLogPrismaClient {
  assistantQueryLog: {
    create(args: { data: Omit<AIQueryLog, 'id' | 'createdAt'> & {
      id: string;
      createdAt: Date;
      retrievedChunks: AIQueryLog['retrievedChunks'];
      sources: AIQueryLog['sources'];
    } }): Promise<unknown>;
    findUnique(args: { where: { id: string } }): Promise<unknown | null>;
    findFirst(args: {
      where: Record<string, unknown>;
      orderBy?: Record<string, unknown>;
    }): Promise<unknown | null>;
    findMany(args: {
      where?: Record<string, unknown>;
      orderBy?: Record<string, unknown>;
      take?: number;
    }): Promise<unknown[]>;
    deleteMany(args: { where: Record<string, unknown> }): Promise<{ count: number }>;
  };
}

export class PrismaAIQueryLogStore implements AIQueryLogStore {
  constructor(private readonly prisma: AIQueryLogPrismaClient) {}

  async append(entry: Omit<AIQueryLog, 'id'>): Promise<AIQueryLog> {
    const id = randomUUID();
    const row: AIQueryLog = {
      ...entry,
      id,
      retrievedChunks: entry.retrievedChunks.map((c) => ({ ...c })),
      sources: entry.sources.map((s) => ({ ...s })),
    };
    await this.prisma.assistantQueryLog.create({ data: { ...row } });
    return row;
  }

  async findById(id: string): Promise<AIQueryLog | null> {
    const raw = await this.prisma.assistantQueryLog.findUnique({ where: { id } });
    return raw ? hydrate(raw) : null;
  }

  async findByTraceId(traceId: string): Promise<AIQueryLog | null> {
    const raw = await this.prisma.assistantQueryLog.findFirst({
      where: { traceId },
      orderBy: { createdAt: 'desc' },
    });
    return raw ? hydrate(raw) : null;
  }

  async list(filter: ListLogsFilter = {}): Promise<AIQueryLog[]> {
    const where: Record<string, unknown> = {};
    if (filter.userId !== undefined) where.userId = filter.userId;
    if (filter.sessionId !== undefined) where.sessionId = filter.sessionId;
    if (filter.since !== undefined || filter.before !== undefined) {
      const range: Record<string, Date> = {};
      if (filter.since !== undefined) range.gte = filter.since;
      if (filter.before !== undefined) range.lt = filter.before;
      where.createdAt = range;
    }
    const rows = await this.prisma.assistantQueryLog.findMany({
      where,
      orderBy: { createdAt: 'desc' },
      take: filter.limit,
    });
    return rows.map(hydrate);
  }

  async pruneOlderThan(cutoff: Date): Promise<number> {
    const result = await this.prisma.assistantQueryLog.deleteMany({
      where: { createdAt: { lt: cutoff } },
    });
    return result.count;
  }
}

function hydrate(raw: unknown): AIQueryLog {
  // The Prisma layer returns plain objects; we trust the schema-aligned
  // shape and only repair the date fields. A misaligned row would have
  // already failed at the database layer.
  const r = raw as AIQueryLog & { createdAt: Date | string };
  return {
    ...r,
    createdAt: r.createdAt instanceof Date ? r.createdAt : new Date(r.createdAt),
  };
}
